export enum EnrolmentStatusReason {
  AUTOMATIC = 1,
  MANUAL,
  PHARMANET_ERROR,
  NOT_IN_PHARMANET,
  NAME_DISCREPANCY,
  BIRTHDATE_DISCREPANCY,
  PRACTICING,
  PUMP_PROVIDER,
  LICENCE_CLASS,
  SELF_DECLARATION,
  ADDRESS,
  ALWAYS_MANUAL,
  ASSURANCE_LEVEL,
  IDENTITY_PROVIDER,
  REQUESTING_REMOTE_ACCESS,
  NO_ASSIGNED_AGREEMENT
}
