export enum ProvisionerCareSettingEnum {
  PRIVATE_COMMUNITY_HEALTH_PRACTICE = 'PCHP',
  COMMUNITY_PHARMACIST = 'CP',
  DEVICE_PROVIDER = 'DP',
  NORTHERN_HEALTH_AUTHORITY = 'NHA',
  INTERIOR_HEALTH_AUTHORITY = 'IHA',
  VANCOUVER_COASTAL_HEALTH_AUTHORITY = 'VCHA',
  VANCOUVER_ISLAND_HEALTH_AUTHORITY = 'VIHA',
  FRASER_HEALTH_AUTHORITY = 'FHA',
  PROVINCIAL_HEALTH_SERVICES_AUTHORITY = 'PHSA',
}
