version: "3"

services:
######################################################### Sign-in #
  sonar-runner:
    container_name: sonar-scanner
    restart: always
    build:
      context: ../
      dockerfile: sonar-scanner/openshift.dockerfile