version: "2"

services:
######################################################### Sign-in #
  sonar-runner:
    container_name: sonar-scanner
    restart: always
    build:
      context: sonar-scanner
      dockerfile: openshift.dockerfile