FROM python:3.6
# USER 0
ENV APP_ROOT /opt/app-root
SHELL ["/bin/bash","-c"]

# Update installation utility
RUN apt-get update -yqq

# Create working directory
RUN mkdir /app
WORKDIR /app

# Install the requirements
COPY requirements.txt .
RUN set -x && \
    pip3 install -r requirements.txt

COPY . .

# ENV FLASK_APP app.py
# ENV DB_HOST postgresql${SUFFIX}
# ENV PGPASSWORD postgres
# Run the server
EXPOSE 5001 9191
CMD ["flask", "db", "upgrade"]
CMD ["tail", "-f", "/dev/null"]