version: "3.0"

services:
# #############################################################################################
# ###                                 Github  BACKEND                                  ###
# #############################################################################################
  github-actor:
    container_name: github-actor
    build:
      context: ./github-actor
      args:
        RUNNER_NAME: ${RUNNER_NAME}
        GITHUB_PAT: ${GITHUB_PAT}
        GITHUB_OWNER: ${GITHUB_OWNER}
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        RUNNER_WORKDIR: ${RUNNER_WORKDIR}
    