{{- if .Values.database.autoCreate }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prime.fullname" . }}-createdb
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    {{- include "prime.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: createdb
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - >
            createdb -O $(APPUSER) $(PGDATABASE) 2> /dev/null || echo "database already exists"
        env:
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: database-host
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: superuser-username
          - name: APPUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: superuser-password
          - name: PGDATABASE
            {{- if $isPR }}
            value: "prime-{{ $drn }}"
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: {{ $release }}-patroni-secret
                key: app-db-name
            {{- end }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
