# This workflow will build PRIME's Angular frontend component image first, then deploy it to the 
# respective OpenShift namespace image registry.

name: Build Angular Frontend Image and Deploy to OpenShift Image Registry

on:
  push:
    branches:
      - feature/prime-1195-1197-ocp4-jenkins
  #     # - fix/*
  #     # - develop
  #     # - test
  #     # - master
  workflow_dispatch:
    branches:
      - feature/prime-1195-1197-ocp4-jenkins
  #     # - fix/*
  #     # - develop
  #     # - test
  #     # - master

jobs:
  build-frontend:
    runs-on: ubuntu-20.04
    environment: Development
    env:
      SERVICE_NAME: nginx-angular
      CONTAINER_NAME: prime-frontend
      IMAGE_TAGS: latest
      JWT_WELL_KNOWN_CONFIG: "https://dev.oidc.gov.bc.ca/auth/realms/v4mbqqas/.well-known/openid-configuration"
      KEYCLOAK_CLIENT_ID: "prime-application-dev"
      KEYCLOAK_URL: "https://dev.oidc.gov.bc.ca/auth"
      KEYCLOAK_REALM: "v4mbqqas"
      REDIRECT_URL: "https://prime-frontend-9c33a9-dev.apps.silver.devops.gov.bc.ca"
      
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v2

      - name: "Login into OpenShift with service account"
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      # Use OpenShift CLI to retrieve necessary environment variables stored in OpenShift to build the frontend
      # - name: "Retrieve OpenShift Keycloak environment variables"
      #   id: oc-env-vars-keycloak
      #   run: |
      #     echo "::set-output name=JWT_WELL_KNOWN_CONFIG::$(oc describe configmap keycloak | grep 'JWT_WELL_KNOWN_CONFIG' -A 2 | grep 'https')"
      #     echo "::set-output name=KEYCLOAK_URL::$(oc describe configmap keycloak | grep 'KEYCLOAK_URL' -A 2 | grep 'https')"
      #     echo "::set-output name=KEYCLOAK_REALM::$(oc describe configmap keycloak | grep 'KEYCLOAK_REALM' -A 2 | grep '[^KEYCLOAK_REALM][a-z]*[0-9]*\w')"
      #     echo "::set-output name=KEYCLOAK_CLIENT_ID::$(oc describe configmap keycloak | grep 'KEYCLOAK_CLIENT_ID' -A 2 | grep '[^KEYCLOAK_CLIENT_ID][a-z]*[0-9]*\w')"
      #   shell: bash

      - name: "Build Angular frontend image"
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker login ${{ secrets.REDHAT_REGISTRY_URL }} -u ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USER }} -p ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_AUTH_TOKEN }}
          docker-compose -f openshift-compose.yml build --force-rm --no-cache \
          --build-arg JWT_WELL_KNOWN_CONFIG=$JWT_WELL_KNOWN_CONFIG \
          --build-arg KEYCLOAK_URL=$KEYCLOAK_URL \
          --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM \
          --build-arg KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID \
          --build-arg REDIRECT_URL=$REDIRECT_URL \
          $SERVICE_NAME

      - name: "Tag Angular frontend to OpenShift image"
        id: tag-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker tag moh-prime_$SERVICE_NAME ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }}/${{ secrets.OPENSHIFT_NAMESPACE }}/$CONTAINER_NAME
      
      - name: "Push Angular frontend image to OpenShift registry"
        id: push-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker login ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }} -u ${{ secrets.OPENSHIFT_SERVICE_ACCOUNT_USERNAME }} -p ${{ secrets.OPENSHIFT_SERVICE_ACCOUNT_PASSWORD }}
          docker image push --all-tags ${{ secrets.OPENSHIFT_IMAGE_REGISTRY }}/${{ secrets.OPENSHIFT_NAMESPACE }}/$CONTAINER_NAME
