version: 2
updates:
  # Nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/prime-dotnet-webapi"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "SoapCore"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/prime-angular-frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
