version: 2
updates:
  # Nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/prime-dotnet-webapi"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/prime-angular-frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
