plugins:
  brakeman:
    enabled: false
  rubocop:
    enabled: false
  eslint:
    enabled: true

exclude_patterns:
# Exclude Folder Pattern
- .github/*
- .docker/*
- .vscode/*
- devops/*
- document-manager/*
- documentation/*
- infrastructure/*
- mailhog/*
- ngork/*
- poc/*
- schemasoy/*
- utilities/*
- prime-e2e-tests/*

# Exclude File Patterns
- "**/*.spec.*"
- "**/*.Designer.cs"
- "prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs"


# examples of minified files that should be excluded
# - **.min.js
# - **.min.css