plugins:
  brakeman:
    enabled: false
  rubocop:
    enabled: false
  eslint:
    enabled: false

# Exclude Folder Pattern
# Exclude File Pattern
exclude_patterns:
- ".github/"
- ".docker/"
- ".vscode/"
- "devops/"
- "document-manager/"
- "documentation/"
- "infrastructure/"
- "mailhog/"
- "ngork/"
- "poc/"
- "prime-database-backup/"
- "prime-angular-frontend/node_modules/"
- "Migrations/"
- "Controllers/"
- "Views/"
- "ViewModels/"
- "Resrouces/"
- "Configuration/"
- "logs/"
- "./prime-dotnet-webapi-tests/"
- "./prime-e2e-tests/"
- "./schemasoy/"
- "./utilities/"
- "./config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/*.spec.*"
- "**/*.json"
- "**/*.html"
- "**/*.cshtml"
- "**/*ViewModel.cs"
- "**/*.Designer.cs"
- "prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs"


# examples of minified files that should be excluded
# - **.min.js
# - **.min.css

# - "./prime-dotnet-webapi/Migrations/"
# - "./prime-dotnet-webapi/Controllers/"
# - "./prime-dotnet-webapi/Views/"
# - "./prime-dotnet-webapi/ViewModels/"
# - "./prime-dotnet-webapi/Resrouces/"
# - "./prime-dotnet-webapi/Configuration/"
# - "./prime-dotnet-webapi/logs/"