plugins:
  brakeman:
    enabled: false
  rubocop:
    enabled: false
  eslint:
    enabled: false

exclude_patterns:
# Exclude Folder Pattern
# - ".github/"
# - ".docker/"
# - ".vscode/"
# - "devops/"
# - "document-manager/"
# - "documentation/"
# - "infrastructure/"
# - "mailhog/"
# - "ngork/"
# - "poc/"
# - "prime-database-backup/"
# - "prime-angular-frontend/node_modules/"
# - "prime-dotnet-webapi/Migrations/"
# - "prime-dotnet-webapi/Controllers/"
# - "prime-dotnet-webapi/Views/"
# - "prime-dotnet-webapi/ViewModels/"
# - "prime-dotnet-webapi/Resrouces/"
# - "prime-dotnet-webapi/Configuration/"
# - "prime-dotnet-webapi/logs/"
# - "prime-dotnet-webapi-tests/"
# - "prime-e2e-tests/"
# - "schemasoy/"
# - "utilities/"

# Auto
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"

# Exclude File Patterns
- "**/*.spec.*"
- "**/*.json"
- "**/*.html"
- "**/*.Designer.cs"
- "prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs"


# examples of minified files that should be excluded
# - **.min.js
# - **.min.css