version: "3"

services:
  ###############################################################################
  ###                     PostgreSQL Database Definition                      ###
  ###############################################################################
  pidp-postgres:
    restart: always
    container_name: pidpdb
    image: postgres:10.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - local_pidp_postgress_data:/var/lib/postgresql/data
    networks:
      - pidp-net

  ###############################################################################
  ###                     PIdP API Backend Definition                         ###
  ###############################################################################
  pidp-webapi:
    container_name: pidp-webapi
    restart: always
    image: pidp
    build:
      context: pidp-webapi/
      args:
        ASPNETCORE_HTTPS_PORT: "5001"
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_URLS: "http://+:8080"
        DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"
    environment:
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"
      ConnectionStrings__PidpDatabase: "host=pidpdb;port=5432;database=postgres;username=postgres;password=postgres"
    volumes:
      - ./pidp-webapi/:/app
      - pidp-webapi-bin:/app/bin
      - pidp-webapi-obj:/app/obj
      - ${APPDATA}/Microsoft/UserSecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b:/root/.microsoft/usersecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b
      # Use the following instead if developing on Mac/Linux:
      # - ${HOME}/.microsoft/usersecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b:/root/.microsoft/usersecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b
    ports:
      - "5050:8080"
      - "5051:5001"
    networks:
      - pidp-net
    depends_on:
      - pidp-postgres
    entrypoint: /bin/bash
    command: [
      "-c",
      "echo Waiting for Database...;
      sleep 15;
      echo \"Running Database Migrations...\";
      dotnet ef database update;
      echo \"Starting API...\";
      dotnet watch run --urls=http://+:8080"
    ]

###############################################################################
###                           Networks Definition                           ###
###############################################################################
networks:
  pidp-net:
    driver: bridge

###############################################################################
###                            Volumes Definition                           ###
###############################################################################
volumes:
  local_pidp_postgress_data: null
  pidp-webapi-bin:
  pidp-webapi-obj:
