version: "3"

services:
###############################################################################
###                     PostgreSQL Database Definition                      ###
###############################################################################
  pip-postgres:
    restart: always
    container_name: pipdb
    image: postgres:10.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - local_pip_postgress_data:/var/lib/postgresql/data
    networks:
      - prime-net

###############################################################################
##                      PIP API Backend Definition                           ##
###############################################################################
  pip-dotnet-webapi:
    container_name: pip-webapi-backend
    restart: always
    image: pip
    build:
      context: pip-dotnet-webapi/
      args:
        ASPNETCORE_HTTPS_PORT: "5001"
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_URLS: "http://+:8080"
        DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"
    environment:
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"
      ConnectionStrings__PipDatabase: "host=pipdb;port=5432;database=postgres;username=postgres;password=postgres"
    volumes:
      - ./pip-dotnet-webapi/:/app
      - pip-dotnet-webapi-bin:/app/bin
      - pip-dotnet-webapi-obj:/app/obj
      - ${APPDATA}/Microsoft/UserSecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b:/root/.microsoft/usersecrets/2144bc8e-373b-4888-a0ca-b0ff7798bd81
      # Use the following instead if developing on Mac/Linux:
      # - ${HOME}/.microsoft/usersecrets/5c2dc965-00b4-4531-9ff0-9b37193ead9b:/root/.microsoft/usersecrets/2144bc8e-373b-4888-a0ca-b0ff7798bd81
    ports:
      - "5050:8080"
      - "5051:5001"
    networks:
      - prime-net
    depends_on:
      - pip-postgres
    entrypoint: /bin/bash
    command: [
      "-c",
      "echo Waiting for Database...;
      sleep 15;
      echo \"Running Database Migrations...\";
      dotnet ef database update;
      echo \"Starting API...\";
      dotnet watch run --urls=http://+:8080"
    ]

###############################################################################
###                           Networks Definition                           ###
###############################################################################
networks:
  prime-net:
    driver: bridge

###############################################################################
###                            Volumes Definition                           ###
###############################################################################
volumes:
  local_pip_postgress_data:
  pip-dotnet-webapi-bin:
  pip-dotnet-webapi-obj:
