version: "3"

services:
####################### API Backend Definition #######################
  dotnet-webapi:
    container_name: prime-webapi-backend
    build:
      context: prime-dotnet-webapi/
      dockerfile: openshift.dockerfile
    networks:
      - openshift

####################### Web Frontend Definition #######################
  nginx-angular:
    container_name: prime-frontend
    build:
      context: prime-angular-frontend/
      dockerfile: openshift.dockerfile
    # command: "nginx -g 'daemon off;'"
    networks:
      - openshift

####################### Local SMTP Server Definition #######################
  mailhog:
    container_name: mailhog
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - 25:1025
      - 1025:1025
      - 8025:8025 # Visit localhost:8025 to see the list of captured emails
    networks:
      - openshift

####################### Database Inspection Definition #######################
  schema-spy:
    container_name: schema-spy
    build:
      context: schemaspy/
    image: openjdk:jre-alpine
    ports:
      - "8069:8069"
      - "80:8069"
    networks:
      - openshift

####################### Backup Definition #######################
  backup:
    container_name: backup
    build:
      context: prime-database-backup
    ports:
      - 6432:5432
      - 9081:8081
    volumes:
      - db_backup_data:/opt/backup
      - local_postgres_data:/var/lib/postgresql/data
    networks:
      - openshift

####################### Document Manager Definition #######################
  document-manager:
    restart: always
    container_name: prime-document-manager
    build:
      context: document-manager/backend
      dockerfile: openshift.dockerfile
      args:
        BUILD_LOGLEVEL: ${BUILD_LOGLEVEL}
    ports:
      - 6001:6001
    volumes:
      - ./document-manager/backend/:/app/
    networks:
      - openshift

####################### Networks Definition #######################
networks:
  openshift:

####################### Volumes Definition #######################
volumes:
  local_postgres_data:
  local_mongodb_data:
  db_backup_data:
