using Microsoft.EntityFrameworkCore.Migrations;

namespace Prime.Migrations
{
    public partial class AddPlrLookups : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PlrExpertiseLookup",
                columns: table => new
                {
                    Code = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlrExpertiseLookup", x => x.Code);
                });

            migrationBuilder.CreateTable(
                name: "PlrRoleTypeLookup",
                columns: table => new
                {
                    Code = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlrRoleTypeLookup", x => x.Code);
                });

            migrationBuilder.CreateTable(
                name: "PlrStatusReasonLookup",
                columns: table => new
                {
                    Code = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlrStatusReasonLookup", x => x.Code);
                });

            migrationBuilder.InsertData(
                table: "PlrExpertiseLookup",
                columns: new[] { "Code", "Name" },
                values: new object[,]
                {
                    { "MS", "Management Studies" },
                    { "SMD78", "Perinatology" },
                    { "SMD77", "Pediatric Rheumatology" },
                    { "117", "Diagnostic Radiology" },
                    { "115", "Dermatology" },
                    { "110", "Community Medicine" },
                    { "108", "Clinical Immunology and Allergy" },
                    { "107", "Clinical Immunology" },
                    { "105", "Cardiology" },
                    { "101", "Anaesthesia" },
                    { "15 ", "Malignant Disease Specialist" },
                    { "302", "Cardiothoracic Surgery" },
                    { "240", "Pathology and Bacteriology" },
                    { "232", "Neuropathology" },
                    { "227", "Medical Microbiology" },
                    { "225", "Medical Biochemistry" },
                    { "215", "Hematological Pathology" },
                    { "210", "General Pathology" },
                    { "SMD79", "Phlebology" },
                    { "202", "Anatomical Pathology" },
                    { "SMD8", "Breastfeeding" },
                    { "SMD81", "Psychiatry" },
                    { "SMD97", "Speech and Hearing Disorders" },
                    { "SMD96", "Burn Surgery" },
                    { "SMD95", "Non-Spine Musculoskeletal Conditions" },
                    { "SMD94", "Urogynecology" },
                    { "SMD93", "Uro - oncology" },
                    { "SMD92", "Treatment of Stress Disorders" },
                    { "SMD91", "Travel Medicine" },
                    { "SMD90", "Sport Medicine" },
                    { "SMD9", "Cardiac Rhythm Disturbances Pacemaker" },
                    { "SMD89", "Sleep Disorders Medicine" },
                    { "SMD88", "Shoulder Surgery" },
                    { "SMD87", "Sclerotherapy of Varicose Veins" },
                    { "SMD86", "Reproductive Endocrinology" },
                    { "SMD85", "Psychotherapy: Indiv.Fam. & Marital" },
                    { "SMD84", "Psychotherapy / Hypnotherapy" },
                    { "SMD83", "Psychotherapy" },
                    { "SMD82", "Psychological Disorders" },
                    { "SMD80", "Phlebology / Sclerotherapy" },
                    { "SMD98", "Oncological Surgery Liver and Pancreas" },
                    { "190", "Therapeutic Radiology" },
                    { "176", "Respirology" },
                    { "465", "Pediatric General Surgery" },
                    { "460", "Nephrology(Int.Med or Ped.)" },
                    { "452", "Medical Oncology(Int.Med.)" },
                    { "435", "Infectious Diseases(Int.Med or Ped.)" },
                    { "432", "Neuropathology" },
                    { "431", "Pediatric Hemat./ Onc. (Pediatrics)" },
                    { "430", "Hematology(Int.Med or Ped.)" },
                    { "425", "Geriatric Medicine(Int.Med.)" },
                    { "420", "Gastroenterology(Int.Med.or Ped.)" },
                    { "417", "Forensic Pathology(Anatomical/ General)" },
                    { "415", "Endocrin.Metabolism(Int.Med.or Ped.)" },
                    { "411", "Critical Care Medicine" },
                    { "305", "Cardiovascular and Thoracic Surgery" },
                    { "409", "Clinical Imm. Allergy(Int.Med.or Ped.)" },
                    { "405", "Cardiology(Int.Med.or Ped.)" },
                    { "360", "Urology" },
                    { "356", "Cardiac Surgery" },
                    { "472", "Respirology(Int.Med.or Ped.)" },
                    { "180", "Rheumatology" },
                    { "118", "Diagnostic and Therapeutic Radiology" },
                    { "126", "Gastroenterology" },
                    { "172", "Radiation Oncology" },
                    { "168", "Public Health" },
                    { "165", "Psychiatry" },
                    { "162", "Physical Medicine Rehabilitation" },
                    { "160", "Pediatrics" },
                    { "159", "Pediatric Cardiology" },
                    { "154", "Community Oncology" },
                    { "153", "Paediatric Oncology" },
                    { "152", "Urological Oncology" },
                    { "151", "Nuclear Medicine" },
                    { "150", "Medical Genetics" },
                    { "149", "No Specialty(Medicine)" },
                    { "146", "Neurology and/ or Psychiatry" },
                    { "145", "Neurology" },
                    { "140", "Medical Scientist(Medicine)" },
                    { "136", "Internal Medicine" },
                    { "130", "Hematology" },
                    { "122", "Emergency Medicine" },
                    { "355", "Thoracic Surgery" },
                    { "SMD99", "Child and Maternal Health" },
                    { "SMD50", "Knee Surgery" },
                    { "SMD47", "Hypnotherapy" },
                    { "SMD46", "Head and Neck Oncology" },
                    { "SMD45", "Hand &Wrist Surgery" },
                    { "SMD44", "Hair Restoration Surgery" },
                    { "SMD43", "Glaucoma" },
                    { "SMD42", "Geriatrics & Psychotherapy" },
                    { "SMD41", "Geriatrics" },
                    { "SMD40", "Geriatric Psychiatry" },
                    { "SMD4", "Allergies -Upper Respiratory Tract" },
                    { "SMD39", "Geriatric Medicine" },
                    { "SMD20", "Dermatopathology" },
                    { "SMD38", "Gastrointestinal Surgery" },
                    { "SMD37", "Forensic Psychiatry Medico-legal Med." },
                    { "SMD36", "Forensic Psychiatry" },
                    { "SMD35", "Forensic Pathology" },
                    { "SMD34", "Female Incontinence & Urodynamics" },
                    { "SMD33", "Family Therapy" },
                    { "SMD48", "Joint Replacement & Reconstruction" },
                    { "SMD32", "Exercise Medicine" },
                    { "LPNORTHO", "Orthopaedic" },
                    { "410", "Clinical Pharmacology" },
                    { "421", "General Internal Medicine" },
                    { "470", "Pain Medicine" },
                    { "426", "Geriatric Psychiatry" },
                    { "418", "Forensic Psychiatry" },
                    { "406", "Child and Adolescent Psychiatry" },
                    { "485", "Transfusion Medicine" },
                    { "468", "Pediatric Radiology" },
                    { "462", "Pediatric Emergency Medicine" },
                    { "461", "Occupational Medicine" },
                    { "455", "Neonatal - Perinatal Medicine" },
                    { "445", "Maternal - Fetal Medicine" },
                    { "434", "Neuroradiology" },
                    { "428", "Gynecologic Reproductive Endocrinology and Infertility" },
                    { "427", "Gynecologic Oncology" },
                    { "423", "General Surgical Oncology" },
                    { "414", "Developmental Pediatrics" },
                    { "412", "Colorectal Surgery" },
                    { "402", "Adolescent Medicine" },
                    { "SMD5", "Arthro.And Reconstruct. Joint Surgery" },
                    { "SMD31", "Endoscopic General Surgery" },
                    { "SMD3", "Allergies" },
                    { "SMD49", "Knee & Leg Surgery" },
                    { "SMD65", "Occupational Medicine" },
                    { "SMD64", "Occupational Health" },
                    { "SMD63", "Occupational & Aviation Medicine" },
                    { "SMD62", "Occupation Related Medical Disorders" },
                    { "SMD61", "Obstetrics &Gynecology" },
                    { "SMD60", "Nutrition" },
                    { "SMD6", "Arthro. And Recon. Surg. (Knee / Shoulder)" },
                    { "SMD59", "Neuroanesthesia" },
                    { "SMD58", "Neuro-otology" },
                    { "SMD57", "Neuro - ophthalmology" },
                    { "SMD56", "Neonatology" },
                    { "SMD55", "Medical Genetics" },
                    { "SMD54", "Maternity Care & Diseases of Females" },
                    { "SMD53", "Mammography" },
                    { "SMD52", "Laser Surgery" },
                    { "SMD51", "Laparoscopic General Surgery" },
                    { "SMD66", "Occupational Ortho. Clinical Impairment" },
                    { "SMD30", "Endocrinology" },
                    { "SMD67", "Oculo-Plastics" },
                    { "SMD69", "OrthopedicSports Medicine in Children" },
                    { "SMD29", "Emergency Care" },
                    { "SMD28", "Echocardiography" },
                    { "SMD27", "Resp. Tract Diseases -Children" },
                    { "SMD26", "Diseases of the Kidney" },
                    { "SMD25", "Diseases of the Joints" },
                    { "SMD24", "Diseases of the Eye" },
                    { "SMD23", "Diseases of the Colon and Rectum" },
                    { "SMD22", "Diseases of Children" },
                    { "SMD21", "Diabetes" },
                    { "SMD76", "Pediatric Otolaryngology" },
                    { "SMD75", "Pediatric Orthopedics" },
                    { "SMD74", "Pediatric Orthopedic Surgery" },
                    { "SMD73", "Pediatric Ophthamology Adult Strabismus" },
                    { "SMD72", "Pediatric &Adolescent Gynecology" },
                    { "SMD71", "Pain Management" },
                    { "SMD70", "Orthopedic Traumatology" },
                    { "SMD7", "Aviation Medicine" },
                    { "SMD68", "Ophthalmology" },
                    { "354", "Thoracic Surgery" },
                    { "155", "Occupational Medicine" },
                    { "345", "Plastic Surgery" },
                    { "LPNDIAL", "Dialysis" },
                    { "GPPHARM", "General Practice" },
                    { "GPMD", "General Practice" },
                    { "GPDEN", "General Practice" },
                    { "ERN9", "Emergency Care/ Prehospital" },
                    { "ERN8", "Operating / Recovery Room" },
                    { "ERN7", "Rehabilitation" },
                    { "ERN6", "Oncology" },
                    { "ERN5", "Psychiatric/ Mental Health" },
                    { "ERN4", "Maternal / Newborn" },
                    { "348", "Principles of Surgery" },
                    { "CCFP", "Certificant; CFPC" },
                    { "ERN2", "General Surgery" },
                    { "ERN19", "Telehealth" },
                    { "ERN18", "Research" },
                    { "ERN17", "Teaching" },
                    { "ERN16", "Nursing Administration" },
                    { "LPNIMMUN", "Immunization" },
                    { "ERN15", "Ambulatory Care" },
                    { "AMD35", "Nuclear Medicine - Full" },
                    { "AMD37", "Magnetic Resonance - Limited" },
                    { "AMD52", "Ultrasound - Abortion Trans - abdominal" },
                    { "AMD51", "Ultrasound -Abortion Transvaginal" },
                    { "AMD50", "Customized Nutritional Therapy(Comp.)" },
                    { "AMD5", "Doctor of Osteopathy" },
                    { "AMD49", "Addiction Medicine" },
                    { "AMD48", "Nuclear Medicine - Restricted" },
                    { "AMD47", "Ultasound - Non-Specialist" },
                    { "AMD46", "Echocardiography -Restricted" },
                    { "AMD45", "Ultrasound - Obstetrical / Gynecology" },
                    { "AMD44", "Homeopathy (Complementary)" },
                    { "AMD43", "Sleep Director - Respiratory Disorders" },
                    { "AMD42", "Sleep Director - Pediatric Disorders" },
                    { "AMD41", "Sleep Director -Full" },
                    { "AMD40", "Pulm Director - Level IV" },
                    { "AMD4", "Craniosacral Therapy(Complementary)" },
                    { "AMD39", "Pulm Director - Level III" },
                    { "AMD38", "Pulm Director - Level II" },
                    { "AMD36", "Sleep Interpreter - Respiratory Dis." },
                    { "AMD53", "Anti-Aging Medicine(Complementary)" },
                    { "ERN14", "Community Health" },
                    { "ERN12", "Home Care" },
                    { "LPNOR", "Operating Room" },
                    { "SMD100", "Medical Disorders of Pregnancy" },
                    { "SMD10", "Certified Independent Medical Examiner" },
                    { "SMD1", "Addiction Medicine" },
                    { "PSYRX", "Psychiatric Pharmacy" },
                    { "PRO", "Prosthodontics" },
                    { "PHPHARM", "Pharmacotherapy" },
                    { "PER", "Periodontics" },
                    { "PED", "Pediatric Dentistry" },
                    { "OS", "Oral Maxillofacial Surgery" },
                    { "ORTH", "Orthodontics" },
                    { "ORD", "Oral and Maxillofacial Radiology" },
                    { "OP", "Oral Medicine and Oral Pathology" },
                    { "ONCRX", "Oncology Pharmacy" },
                    { "NUTRX", "Nutrition Pharmacy" },
                    { "NUCRX", "Nuclear Pharmacy" },
                    { "NON-SPEC", "Non-Specialist" },
                    { "SMD101", "Cardiovascular Disease" },
                    { "ERN13", "Geriatric / Long Term Care" },
                    { "SMD104", "Chemical, Biological, Radiological and Nuclear Warfare Medicine" },
                    { "SMD12", "Child and Adolescent Psychiatry" },
                    { "ERN11", "Occupational Health" },
                    { "ERN10", "Critical/ Intensive Care" },
                    { "ERN1", "General Medicine" },
                    { "END", "Endodontics" },
                    { "DS", "Dental Sciences" },
                    { "DPH", "Dental Public Health" },
                    { "CTI", "Computed Tomography Imaging" },
                    { "CMCE", "Community Medicine Certification" },
                    { "CCFPEM", "Certificant; CFPC(E.M.)" },
                    { "SMD2", "Adolescent Medicine" },
                    { "SMD19", "Dermatology" },
                    { "SMD18", "Critical Care Medicine" },
                    { "SMD17", "Counseling" },
                    { "SMD16", "Corneal & Extraocular Disease" },
                    { "SMD15", "Colon & Rectal Surgery" },
                    { "SMD14", "Clinical Hypnosis" },
                    { "SMD13", "Chronic Pain Management" },
                    { "SMD11", "Chemical Dependency" },
                    { "AMD54", "Primordial Sound Meditation(Complementary)" },
                    { "ERN3", "Pediatrics" },
                    { "AMD56", "Fluoroscopically-guided needle placements" },
                    { "905", "Pediatric Nephrology" },
                    { "900", "Pediatric Gastroenterology" },
                    { "474", "Rheumatology(Int.Med or Ped.)" },
                    { "584", "Developmental Pediatrics" },
                    { "582", "Pediatric Emergency Medicine" },
                    { "580", "Pediatric Radiology" },
                    { "570", "Palliative Medicine" },
                    { "560", "Neuroradiology" },
                    { "555", "Neonatal - Perinatal Medicine" },
                    { "550", "Clinician Investigator Program" },
                    { "545", "Maternal - Fetal Medicine" },
                    { "540", "Transfusion Medicine" },
                    { "535", "Gynecology Reprod. Endocrin. & Infert." },
                    { "530", "Gynecology Oncology" },
                    { "520", "General Surgical Oncology" },
                    { "515", "Critical Care medicine" },
                    { "512", "Colorectal Surgery" },
                    { "910", "Pediatric Neurology" },
                    { "510", "Clinical Pharmacology" },
                    { "915", "Pediatric Cardiovascular Surgery" },
                    { "A115", "Adolescent Medicine" },
                    { "342", "Otolaryngology" },
                    { "340", "Orthopedic Surgery" },
                    { "338", "Ophthalmology" },
                    { "336", "Obstetrics and Gynecology" },
                    { "331", "No Specialty(Surgery)" },
                    { "329", "Neurosurgery" },
                    { "AMD55", "Ayurveda(Complementary)" },
                    { "320", "Obstetrics" },
                    { "319", "Gynecology" },
                    { "315", "General Surgery" },
                    { "A160", "Family Medicine" },
                    { "A155", "Epidemiology" },
                    { "A145", "Cytopathology" },
                    { "A140", "Child Health" },
                    { "A135", "Behavioral Therapy" },
                    { "A130", "Aviation Medicine" },
                    { "A120", "Allergy" },
                    { "A110", "dministrative Medicine" },
                    { "490", "Vascular Surgery" },
                    { "325", "Medical Scientist(Surgery)" },
                    { "480", "Thoracic Surgery(Gen.Sur.)" },
                    { "AMD15", "Kinesiology(Complementary)" },
                    { "AMD14", "Herbal Therapy(Complementary)" },
                    { "AMD13", "Functional Medicine(Complementary)" },
                    { "AMD12", "Evoked Potential(EP)" },
                    { "AMD11", "Evoked Potential Visual" },
                    { "AMD10", "Evoked Potential Somatosensory" },
                    { "A385", "Pulmonary Diseases" },
                    { " A240", "Medical Imaging" },
                    { "A225", "Max / Fax Surgery" },
                    { "BI", "Breast Imaging" },
                    { "AMD9", "Evoked Potential Auditory" },
                    { "AMD8", "Electromyography" },
                    { "AMD7", "Electroencephalography" },
                    { "AMD6", "Electrocardiogram" },
                    { "AMD58", "PET -Positron Emission Tomography" },
                    { "AMD57", "Magnetic Resonance - Cardiac" },
                    { "481", "Thoracic Surgery(General / Cardiac)" },
                    { "AMD16", "Magnetic Resonance - Full" },
                    { "AMD17", "Cardiac Nuclear Imaging" },
                    { "AMD1", "Acupuncture" },
                    { "AMD19", "Ultrasound - Opthalmology" },
                    { "AMD34", "Chelation Therapy(Complementary)" },
                    { "AMD18", "Nuclear Medicine - Limited" },
                    { "AMD32", "Vestibular Testing - Director" },
                    { "AMD31", "Ultrasound -Vascular" },
                    { "AMD30", "Ultrasound -Urology" },
                    { "AMD3", "Cardiac Stress Testing" },
                    { "AMD29", "Ultrasound -Full" },
                    { "AMD28", "Trigger Point Therapy" },
                    { "AMD27", "Echocardiography -Transesophageal" },
                    { "AMD33", "Vestibular Testing - Interpretor" },
                    { "AMD25", "Thought Field Therapy(Complementary)" },
                    { "AMD24", "Reiki Therapy(Complementary)" },
                    { "AMD23", "Pulm Interpretation-Level IV" },
                    { "AMD22", "Pulm Interpretation-Level III" },
                    { "AMD21", "Pulm Interpretation-Level II" },
                    { "AMD20", "Echocardiography - Full Pediatric" },
                    { "AMD2", "Echocardiography -Full Adult" },
                    { "AMD26", "Transcendental Meditation(Comp.)" }
                });

            migrationBuilder.InsertData(
                table: "PlrRoleTypeLookup",
                columns: new[] { "Code", "Name" },
                values: new object[,]
                {
                    { "ACP", "Advanced Care Paramedic" },
                    { "CCP", "Critical Care Paramedic" },
                    { "DEN", "Dentist" },
                    { "EMR", "Emergency Medical Responder" },
                    { "CC", "Clinical Counsellor" },
                    { "OT", "Occupational Therapist" },
                    { "PSYCH", "Psychologist" },
                    { "SW", "Social Worker" },
                    { "RMT", "Registered Massage Therapist" },
                    { "CHIRO", "Chiropractor" },
                    { "PHYSIO", "Physiotherapist" },
                    { "KN", "Kinesiologist" },
                    { "PTECH", "Pharmacy Technician" },
                    { "COUN", "Counsellor" },
                    { "MFT", "Marriage and Family Therapist" },
                    { "RD", "Registered Dietitian" },
                    { "PHARMTECH", "PHARMTECH" },
                    { "RCSW", "Registered Clinical Social Worker" },
                    { "PCY", "Pharmacy" },
                    { "LPN", "Licensed Practical Nurse" },
                    { "OPT", "Optometrist" },
                    { "PCP", "Primary Care Paramedic" },
                    { "RTNM", "Nuclear Medicine Technologist" },
                    { "RTT", "Radiation Technologist in Therapy" },
                    { "RN", "Registered Nurse" },
                    { "RNP", "Registered Nurse Practitioner" },
                    { "RPN", "Registered Psychiatric Nurse" },
                    { "RTEMG", "Registered Electromyography Technologist" },
                    { "RTMR", "Radiation Technologist in Magnetic Resonance" },
                    { "RTR", "Radiation Technologist in Radiology" },
                    { "PO", "Podiatrist" },
                    { "RAC", "Registered Acupuncturist" },
                    { "REPT", "Registered Evoked Potential Technologist" },
                    { "RET", "Registered Electroencephalography Technologist" },
                    { "RM", "Registered Midwife" },
                    { "MD", "Medical Doctor" },
                    { "PHARM", "Pharmacist" },
                    { "MOA", "Medical Office Assistant" }
                });

            migrationBuilder.InsertData(
                table: "PlrStatusReasonLookup",
                columns: new[] { "Code", "Name" },
                values: new object[,]
                {
                    { "TI", "Temporary Inactive" },
                    { "TSF", "Transfer" },
                    { "UNK", "Unknown" },
                    { "VW", "Voluntary Withdrawal" },
                    { "ASSOC", "Associate" },
                    { "LAP", "License Lapsed on Request" },
                    { "CLOSED", "Closed" },
                    { "NONPRAC", "Non Practicing" },
                    { "LTP", "Left the Province" },
                    { "NONPAY", "Non Payment of Fee" },
                    { "RET", "Retired" },
                    { "TEMPPER", "Temporary Permit" },
                    { "AU", "Address Unknown" },
                    { "SUS", "Suspended" },
                    { "HON", "Honorary" },
                    { "RESDISC", "Resigned - disciplinary action" },
                    { "REM", "Removed" },
                    { "PRAC", "Practising" },
                    { "OPEN", "Open" },
                    { "NR", "Non-resident" },
                    { "MIS", "Missionary" },
                    { "INNONPRAC", "Initial Non Practicing" },
                    { "GS", "Good Standing" },
                    { "ERSRES", "Erased by Resolution" },
                    { "DEN", "Licensed Denied" },
                    { "DEF", "Deferred" },
                    { "ORG", "Organization Provider" },
                    { "OOP", "Out of Province" },
                    { "DEC", "Deceased" },
                    { "SPE", "Special Registry" },
                    { "MEDSTUD", "Medical Student" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PlrExpertiseLookup");

            migrationBuilder.DropTable(
                name: "PlrRoleTypeLookup");

            migrationBuilder.DropTable(
                name: "PlrStatusReasonLookup");
        }
    }
}
