// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prime;
using Prime.Models;

namespace Prime.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Prime.Models.Address", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressType");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<int>("EnrolleeId");

                    b.Property<string>("Postal");

                    b.Property<string>("Province");

                    b.Property<string>("Street");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("EnrolleeId", "AddressType")
                        .IsUnique()
                        .HasName("IX_EnrolleeId_AddressType");

                    b.ToTable("Address");

                    b.HasDiscriminator<int>("AddressType");
                });

            modelBuilder.Entity("Prime.Models.Certification", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("CollegeCode");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<int>("EnrolmentId");

                    b.Property<short>("LicenseCode");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<short?>("PracticeCode");

                    b.Property<DateTime>("RenewalDate");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("CollegeCode");

                    b.HasIndex("EnrolmentId");

                    b.HasIndex("LicenseCode");

                    b.HasIndex("PracticeCode");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("Prime.Models.College", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Prefix");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("CollegeLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "College of Physicians and Surgeons of BC (CPSBC)",
                            Prefix = "91",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "College of Pharmacists of BC (CPBC)",
                            Prefix = "P1",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "College of Registered Nurses of BC (CRNBC)",
                            Prefix = "96",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "None",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.CollegeLicense", b =>
                {
                    b.Property<short>("CollegeCode");

                    b.Property<short>("LicenseCode");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("CollegeCode", "LicenseCode");

                    b.HasIndex("LicenseCode");

                    b.ToTable("CollegeLicense");

                    b.HasData(
                        new
                        {
                            CollegeCode = (short)1,
                            LicenseCode = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)1,
                            LicenseCode = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            LicenseCode = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            LicenseCode = (short)5,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            LicenseCode = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            LicenseCode = (short)5,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.CollegePractice", b =>
                {
                    b.Property<short>("CollegeCode");

                    b.Property<short>("PracticeCode");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("CollegeCode", "PracticeCode");

                    b.HasIndex("PracticeCode");

                    b.ToTable("CollegePractice");

                    b.HasData(
                        new
                        {
                            CollegeCode = (short)1,
                            PracticeCode = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)1,
                            PracticeCode = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)1,
                            PracticeCode = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)1,
                            PracticeCode = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            PracticeCode = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            PracticeCode = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            PracticeCode = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)2,
                            PracticeCode = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            PracticeCode = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            PracticeCode = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            PracticeCode = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CollegeCode = (short)3,
                            PracticeCode = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.Enrollee", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.Property<string>("PreferredFirstName");

                    b.Property<string>("PreferredLastName");

                    b.Property<string>("PreferredMiddleName");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.Property<Guid>("UserId");

                    b.Property<string>("VoiceExtension");

                    b.Property<string>("VoicePhone");

                    b.HasKey("Id");

                    b.ToTable("Enrollee");
                });

            modelBuilder.Entity("Prime.Models.Enrolment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppliedDate");

                    b.Property<bool?>("Approved");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<string>("ApprovedReason");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("DeviceProviderNumber")
                        .HasMaxLength(5);

                    b.Property<string>("DeviceProviderPrefix");

                    b.Property<int>("EnrolleeId");

                    b.Property<bool?>("HasCertification");

                    b.Property<bool?>("HasConviction");

                    b.Property<string>("HasConvictionDetails");

                    b.Property<bool?>("HasDisciplinaryAction");

                    b.Property<string>("HasDisciplinaryActionDetails");

                    b.Property<bool?>("HasPharmaNetSuspended");

                    b.Property<string>("HasPharmaNetSuspendedDetails");

                    b.Property<bool?>("HasRegistrationSuspended");

                    b.Property<string>("HasRegistrationSuspendedDetails");

                    b.Property<bool?>("IsAccessingPharmaNetOnBehalfOf");

                    b.Property<bool?>("IsDeviceProvider");

                    b.Property<bool?>("IsInsulinPumpProvider");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("EnrolleeId");

                    b.ToTable("Enrolment");
                });

            modelBuilder.Entity("Prime.Models.EnrolmentStatus", b =>
                {
                    b.Property<int>("EnrolmentId");

                    b.Property<short>("StatusCode");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<bool>("IsCurrent");

                    b.Property<DateTime>("StatusDate");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("EnrolmentId", "StatusCode");

                    b.HasIndex("StatusCode");

                    b.ToTable("EnrolmentStatus");
                });

            modelBuilder.Entity("Prime.Models.Job", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<int>("EnrolmentId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("EnrolmentId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Prime.Models.JobName", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("JobNameLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Medical Office Assistant",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Midwife",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Nurse (not nurse practitioner)",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Pharmacy Assistant",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)5,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Pharmacy Technician",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)6,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Registration Clerk",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)7,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Ward Clerk",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)8,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Other",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.License", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("LicenseLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Full - General",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Full - Pharmacist",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Full - Specialty",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Registered Nurse",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)5,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Temporary Registered Nurse",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.Organization", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("EnrolmentId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<short>("OrganizationTypeCode");

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Id");

                    b.HasIndex("EnrolmentId");

                    b.HasIndex("OrganizationTypeCode");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Prime.Models.OrganizationName", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("OrganizationNameLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Vancouver Island Health",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Shoppers Drug Mart",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.OrganizationType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("OrganizationTypeLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Health Authority",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Pharmacy",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.Practice", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("PracticeLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Remote Practice",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Reproductive Care",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Sexually Transmitted Infections (STI)",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "None",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.Status", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTimeStamp");

                    b.Property<Guid>("CreatedUserId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedTimeStamp");

                    b.Property<Guid>("UpdatedUserId");

                    b.HasKey("Code");

                    b.ToTable("StatusLookup");

                    b.HasData(
                        new
                        {
                            Code = (short)1,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "In Progress",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)2,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Submitted",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)3,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Approved",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)4,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Denied",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Code = (short)5,
                            CreatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Accepted",
                            UpdatedTimeStamp = new DateTime(2019, 10, 17, 13, 11, 39, 787, DateTimeKind.Local).AddTicks(498),
                            UpdatedUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Prime.Models.MailingAddress", b =>
                {
                    b.HasBaseType("Prime.Models.Address");

                    b.HasIndex("EnrolleeId")
                        .HasName("IX_Address_EnrolleeId");

                    b.ToTable("Address");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Prime.Models.PhysicalAddress", b =>
                {
                    b.HasBaseType("Prime.Models.Address");

                    b.HasIndex("EnrolleeId")
                        .HasName("IX_Address_EnrolleeId");

                    b.ToTable("Address");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Prime.Models.Certification", b =>
                {
                    b.HasOne("Prime.Models.College", "College")
                        .WithMany("Certifications")
                        .HasForeignKey("CollegeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.Enrolment", "Enrolment")
                        .WithMany("Certifications")
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.License", "License")
                        .WithMany("Certifications")
                        .HasForeignKey("LicenseCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.Practice", "Practice")
                        .WithMany("Certifications")
                        .HasForeignKey("PracticeCode");
                });

            modelBuilder.Entity("Prime.Models.CollegeLicense", b =>
                {
                    b.HasOne("Prime.Models.College", "College")
                        .WithMany("CollegeLicenses")
                        .HasForeignKey("CollegeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.License", "License")
                        .WithMany("CollegeLicenses")
                        .HasForeignKey("LicenseCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.CollegePractice", b =>
                {
                    b.HasOne("Prime.Models.College", "College")
                        .WithMany("CollegePractices")
                        .HasForeignKey("CollegeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.Practice", "Practice")
                        .WithMany("CollegePractices")
                        .HasForeignKey("PracticeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.Enrolment", b =>
                {
                    b.HasOne("Prime.Models.Enrollee", "Enrollee")
                        .WithMany("Enrolments")
                        .HasForeignKey("EnrolleeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.EnrolmentStatus", b =>
                {
                    b.HasOne("Prime.Models.Enrolment", "Enrolment")
                        .WithMany("EnrolmentStatuses")
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.Status", "Status")
                        .WithMany("EnrolmentStatuses")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.Job", b =>
                {
                    b.HasOne("Prime.Models.Enrolment", "Enrolment")
                        .WithMany("Jobs")
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.Organization", b =>
                {
                    b.HasOne("Prime.Models.Enrolment", "Enrolment")
                        .WithMany("Organizations")
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prime.Models.OrganizationType", "OrganizationType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrganizationTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.MailingAddress", b =>
                {
                    b.HasOne("Prime.Models.Enrollee", "Enrollee")
                        .WithOne("MailingAddress")
                        .HasForeignKey("Prime.Models.MailingAddress", "EnrolleeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Prime.Models.PhysicalAddress", b =>
                {
                    b.HasOne("Prime.Models.Enrollee", "Enrollee")
                        .WithOne("PhysicalAddress")
                        .HasForeignKey("Prime.Models.PhysicalAddress", "EnrolleeId")
                        .HasConstraintName("FK_Address_Enrollee_EnrolleeId1")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
