"""

Revision ID: 6f27a6937206
Revises: 7eefdf5d93c4
Create Date: 2020-09-21 18:00:00.0

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6f27a6937206'
down_revision = '7eefdf5d93c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('submitted', sa.Boolean(), nullable=False, default=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'submitted')
    # ### end Alembic commands ###
