# PR Helm values
global:
  vanityURL: "pr-9000.pharmanetenrolment.gov.bc.ca"
  image:
    tag: dev

redis:
  enabled: true
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password