using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prime.Models;

namespace Prime.Configuration.Database
{
    public class LicenseDetailConfiguration : SeededTable<LicenseDetail>
    {
        public static readonly DateTime ImRegUpdate1Date = new(2022, 2, 1, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime ImRegUpdateTempRollforwardDate = new(2022, 5, 1, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime June1st2022Cohort = new(2022, 6, 1, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime July15th2022 = new(2022, 7, 15, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime Aug1st2022 = new(2022, 8, 1, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime LicenceClassUpdateAug5th2022 = new(2022, 8, 5, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime EnableNonPrescriberPrefixAug10th2022 = new(2022, 8, 10, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime SetPractIdToMandatorySept6th2022 = new(2022, 9, 6, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime SetPractIdToMandatoryFeb2nd2023 = new(2023, 2, 2, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime SetValidateForNurseMarch15th2023 = new(2023, 3, 15, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime June9th2023 = new(2023, 6, 9, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime AdjustmentsToOnboardCollegeOfOptometristsAug2nd2023 = new(2023, 8, 2, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime AdjustmentsToCPSBCAug28th2023 = new(2023, 8, 28, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime EmployedStudentNurseChangeAug28th2023 = new(2023, 8, 28, 8, 0, 0, DateTimeKind.Utc);
        public static readonly DateTime PhysicalAssistantChangeAug28th2023 = new(2023, 11, 27, 8, 0, 0, DateTimeKind.Utc);

        public override IEnumerable<LicenseDetail> SeedData
        {
            get
            {
                return new[] {
                    // CPSBC
                    new LicenseDetail { Id = 1,  LicenseCode = 1,  Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 2,  LicenseCode = 2,  Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 5,  LicenseCode = 5,  Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 6,  LicenseCode = 6,  Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 9,  LicenseCode = 9,  Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 8,  LicenseCode = 8,  Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 10, LicenseCode = 10, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 22, LicenseCode = 22, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 16, LicenseCode = 16, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 7,  LicenseCode = 7,  Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 4,  LicenseCode = 4,  Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 3,  LicenseCode = 3,  Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 17, LicenseCode = 17, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 12, LicenseCode = 12, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 13, LicenseCode = 13, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 14, LicenseCode = 14, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 15, LicenseCode = 15, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 11, LicenseCode = 11, Prefix = "91", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 23, LicenseCode = 23, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 20, LicenseCode = 20, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 24, LicenseCode = 24, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 18, LicenseCode = 18, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 19, LicenseCode = 19, Prefix = "91", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 21, LicenseCode = 21, Prefix = "91", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 59, LicenseCode = 59, Prefix = "93", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 65, LicenseCode = 65, Prefix = "93", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 66, LicenseCode = 66, Prefix = "93", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 67, LicenseCode = 67, Prefix = "93", Manual = true,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Pharmacy
                    new LicenseDetail { Id = 25, LicenseCode = 25, Prefix = "P1", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 26, LicenseCode = 26, Prefix = "P1", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 28, LicenseCode = 28, Prefix = "P1", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 27, LicenseCode = 27, Prefix = "P1", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 30, LicenseCode = 30, Prefix = "P1", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 29, LicenseCode = 29, Prefix = "T9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 31, LicenseCode = 31, Prefix = "T9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 68, LicenseCode = 68, Prefix = "T9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 70, LicenseCode = 29, Prefix = "T9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 71, LicenseCode = 31, Prefix = "T9", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 72, LicenseCode = 68, Prefix = "T9", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Nursing
                    new LicenseDetail { Id = 47, LicenseCode = 47, Prefix = "96", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 48, LicenseCode = 48, Prefix = "96", Manual = true,  Validate = false, NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 51, LicenseCode = 51, Prefix = "96", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 49, LicenseCode = 49, Prefix = "96", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false,                                                EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 32, LicenseCode = 32, Prefix = "R9", Manual = false, Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 33, LicenseCode = 33, Prefix = "R9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 39, LicenseCode = 39, Prefix = "R9", Manual = false, Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 34, LicenseCode = 34, Prefix = "R9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                                EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 40, LicenseCode = 40, Prefix = "R9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 35, LicenseCode = 35, Prefix = "R9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 36, LicenseCode = 36, Prefix = "R9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 37, LicenseCode = 37, Prefix = "R9", Manual = false, Validate = true,  NamedInImReg = false, LicensedToProvideCare = false,                                                EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 41, LicenseCode = 41, Prefix = "Y9", Manual = false, Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 42, LicenseCode = 42, Prefix = "Y9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 45, LicenseCode = 45, Prefix = "Y9", Manual = false, Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional,  EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 43, LicenseCode = 43, Prefix = "Y9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                                EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 46, LicenseCode = 46, Prefix = "Y9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 52, LicenseCode = 52, Prefix = "L9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 53, LicenseCode = 53, Prefix = "L9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 55, LicenseCode = 55, Prefix = "L9", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 54, LicenseCode = 54, Prefix = "L9", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                                EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 60, LicenseCode = 60, Prefix = "98", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 61, LicenseCode = 61, Prefix = "98", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 62, LicenseCode = 62, Prefix = "98", Manual = false, Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 63, LicenseCode = 63, Prefix = "98", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 69, LicenseCode = 69, Prefix = "98", Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                 EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Dental Surgeons
                    new LicenseDetail { Id = 89, LicenseCode = 70, Prefix = "95", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Optometrists
                    new LicenseDetail { Id = 90, LicenseCode = 71, Prefix = "94", Manual = false, Validate = true, NamedInImReg = true,   LicensedToProvideCare = true, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 91, LicenseCode = 72, Prefix = "94", Manual = false, Validate = true, NamedInImReg = false,  LicensedToProvideCare = true, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 92, LicenseCode = 73, Prefix = "94", Manual = false, Validate = true, NamedInImReg = false,  LicensedToProvideCare = true, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 93, LicenseCode = 74, Prefix = "94", Manual = false, Validate = true, NamedInImReg = false,  LicensedToProvideCare = true, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // February 1st, 2022 Nursing IMReg February 1st Updates
                    new LicenseDetail { Id = 73, LicenseCode = 32, Prefix = "R9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 74, LicenseCode = 33, Prefix = "R9", Manual = true,  Validate = false, NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 75, LicenseCode = 34, Prefix = "R9", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false,                                                EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 76, LicenseCode = 39, Prefix = "R9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 77, LicenseCode = 41, Prefix = "Y9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 78, LicenseCode = 42, Prefix = "Y9", Manual = true,  Validate = false, NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 79, LicenseCode = 43, Prefix = "Y9", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false,                                                EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 80, LicenseCode = 45, Prefix = "Y9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 81, LicenseCode = 52, Prefix = "L9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 82, LicenseCode = 53, Prefix = "L9", Manual = true,  Validate = false, NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 83, LicenseCode = 54, Prefix = "L9", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false,                                                EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 84, LicenseCode = 55, Prefix = "L9", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 85, LicenseCode = 60, Prefix = "98", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 86, LicenseCode = 61, Prefix = "98", Manual = true,  Validate = false, NamedInImReg = true,  LicensedToProvideCare = true,                                                 EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 87, LicenseCode = 62, Prefix = "98", Manual = false, Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Mandatory, EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 88, LicenseCode = 63, Prefix = "98", Manual = true,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = false,                                                EffectiveDate = ImRegUpdate1Date, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // May 1st, 2022 Nursing ImReg Updates Rolling Back due to not all nurses being assigned PharmanNet Id Yet, Will Roll forward by coherts
                    new LicenseDetail { Id = 94,  LicenseCode = 32, Prefix = "R9", Manual = false,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional, EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 95,  LicenseCode = 33, Prefix = "R9", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 96,  LicenseCode = 34, Prefix = "R9", Manual = true,   Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                               EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 97,  LicenseCode = 39, Prefix = "R9", Manual = false,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional, EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 98,  LicenseCode = 41, Prefix = "Y9", Manual = false,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional, EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 99,  LicenseCode = 42, Prefix = "Y9", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 100, LicenseCode = 43, Prefix = "Y9", Manual = true,   Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                               EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 101, LicenseCode = 45, Prefix = "Y9", Manual = false,  Validate = true,  NamedInImReg = false, LicensedToProvideCare = true,  PrescriberIdType = PrescriberIdType.Optional, EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 102, LicenseCode = 52, Prefix = "L9", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 103, LicenseCode = 53, Prefix = "L9", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 104, LicenseCode = 54, Prefix = "L9", Manual = true,   Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                               EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 105, LicenseCode = 55, Prefix = "L9", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 106, LicenseCode = 60, Prefix = "98", Manual = false,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 107, LicenseCode = 61, Prefix = "98", Manual = false,  Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 108, LicenseCode = 63, Prefix = "98", Manual = true,   Validate = false, NamedInImReg = false, LicensedToProvideCare = false,                                               EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 109, LicenseCode = 62, Prefix = "98", Manual = false,  Validate = true,  NamedInImReg = true,  LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 110, LicenseCode = 48, Prefix = "96", Manual = true,   Validate = false, NamedInImReg = false, LicensedToProvideCare = true,                                                EffectiveDate = ImRegUpdateTempRollforwardDate, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    //June 1st, 2022 Onboarding Podiatrists, Dental Surgeons, and Naturopaths
                    new LicenseDetail { Id = 111, LicenseCode = 59, Prefix = "93", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 112, LicenseCode = 65, Prefix = "93", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 113, LicenseCode = 66, Prefix = "93", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 114, LicenseCode = 67, Prefix = "93", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 115, LicenseCode = 70, Prefix = "95", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 116, LicenseCode = 75, Prefix = "95", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 117, LicenseCode = 76, Prefix = "95", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 118, LicenseCode = 77, Prefix = "95", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 119, LicenseCode = 78, Prefix = "97", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 120, LicenseCode = 79, Prefix = "97", Manual = false, Validate = true, NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 121, LicenseCode = 80, Prefix = "97", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 122, LicenseCode = 81, Prefix = "97", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true,  EffectiveDate = June1st2022Cohort, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // All other colleges are assigned the "Not Displayed"Type
                    new LicenseDetail { Id = 64, LicenseCode = 64, Prefix = "",   Manual = true,  Validate = false, NamedInImReg = false, LicensedToProvideCare = false, EffectiveDate = SEEDING_DATE.DateTime.ToUniversalTime(), CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    //July 15th, 2022 Use new flag AllowRequestRemoteAccess to control Request Remote Access option in PRIME
                    new LicenseDetail { Id =  123, LicenseCode = 1, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  124, LicenseCode = 2, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  125, LicenseCode = 3, Prefix = "91", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  126, LicenseCode = 4, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  127, LicenseCode = 5, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  128, LicenseCode = 6, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  129, LicenseCode = 8, Prefix = "91", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  130, LicenseCode = 9, Prefix = "91", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  131, LicenseCode = 10, Prefix = "91", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  132, LicenseCode = 12, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  133, LicenseCode = 13, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  134, LicenseCode = 14, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  135, LicenseCode = 18, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  136, LicenseCode = 19, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  137, LicenseCode = 22, Prefix = "91", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  138, LicenseCode = 47, Prefix = "96", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  139, LicenseCode = 48, Prefix = "96", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  140, LicenseCode = 51, Prefix = "96", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  141, LicenseCode = 59, Prefix = "93", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  142, LicenseCode = 60, Prefix = "98", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  143, LicenseCode = 61, Prefix = "98", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  144, LicenseCode = 62, Prefix = "98", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  145, LicenseCode = 66, Prefix = "93", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  146, LicenseCode = 67, Prefix = "93", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true,  EffectiveDate = July15th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    //August 1st enrolment logic change
                    new LicenseDetail { Id =  147, LicenseCode = 41, Prefix = "Y9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false,  EffectiveDate = Aug1st2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  148, LicenseCode = 42, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false,  EffectiveDate = Aug1st2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  149, LicenseCode = 43, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false,  EffectiveDate = Aug1st2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  150, LicenseCode = 45, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false,  EffectiveDate = Aug1st2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  151, LicenseCode = 46, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false,  EffectiveDate = Aug1st2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    //August 5th licence class update to fix number of issues, including LPN and RPN getting incorrect TOA
                    new LicenseDetail { Id = 152, LicenseCode = 65, Prefix = "93", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 153, LicenseCode = 32, Prefix = "R9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 154, LicenseCode = 33, Prefix = "R9", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 155, LicenseCode = 34, Prefix = "R9", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 156, LicenseCode = 35, Prefix = "R9", NamedInImReg = true, LicensedToProvideCare = true, Manual = true, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 157, LicenseCode = 36, Prefix = "R9", NamedInImReg = false, LicensedToProvideCare = true, Manual = true, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 158, LicenseCode = 37, Prefix = "R9", NamedInImReg = true, LicensedToProvideCare = false, Manual = false, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 159, LicenseCode = 39, Prefix = "R9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 160, LicenseCode = 41, Prefix = "Y9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 161, LicenseCode = 42, Prefix = "Y9", NamedInImReg = false, LicensedToProvideCare = true, Manual = true, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 162, LicenseCode = 43, Prefix = "Y9", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 163, LicenseCode = 45, Prefix = "Y9", NamedInImReg = true, LicensedToProvideCare = true, Manual = true, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 164, LicenseCode = 46, Prefix = "Y9", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 165, LicenseCode = 47, Prefix = "96", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 166, LicenseCode = 48, Prefix = "96", NamedInImReg = false, LicensedToProvideCare = true, Manual = true, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 167, LicenseCode = 49, Prefix = "96", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 168, LicenseCode = 51, Prefix = "96", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 169, LicenseCode = 52, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 170, LicenseCode = 53, Prefix = "L9", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 171, LicenseCode = 54, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 172, LicenseCode = 55, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 173, LicenseCode = 60, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 174, LicenseCode = 61, Prefix = "98", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 175, LicenseCode = 62, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 176, LicenseCode = 63, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = LicenceClassUpdateAug5th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    //August 10th populate non-prescribing prefix
                    new LicenseDetail { Id =  177, LicenseCode = 47, Prefix = "96", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  178, LicenseCode = 48, Prefix = "96", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  179, LicenseCode = 49, Prefix = "96", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "NX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  180, LicenseCode = 51, Prefix = "96", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    new LicenseDetail { Id =  181, LicenseCode = 32, Prefix = "R9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  182, LicenseCode = 33, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  183, LicenseCode = 34, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  184, LicenseCode = 35, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  185, LicenseCode = 36, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  186, LicenseCode = 37, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  187, LicenseCode = 39, Prefix = "R9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  188, LicenseCode = 40, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    new LicenseDetail { Id =  189, LicenseCode = 41, Prefix = "Y9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  190, LicenseCode = 42, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  191, LicenseCode = 43, Prefix = "Y9", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  192, LicenseCode = 45, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  193, LicenseCode = 46, Prefix = "Y9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = EnableNonPrescriberPrefixAug10th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    // 2022-09-06 PractId should be Optional -> Mandatory for RPNs, NPs, and Midwives.  For these licence classes, Validate PractId
                    new LicenseDetail { Id =  194, LicenseCode = 41, Prefix = "Y9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  195, LicenseCode = 42, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  196, LicenseCode = 45, Prefix = "Y9", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    new LicenseDetail { Id =  197, LicenseCode = 47, Prefix = "96", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  198, LicenseCode = 48, Prefix = "96", Manual = true, Validate = true,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  199, LicenseCode = 51, Prefix = "96", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, NonPrescribingPrefix = "NX", EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},

                    new LicenseDetail { Id = 200, LicenseCode = 60, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 201, LicenseCode = 61, Prefix = "98", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 202, LicenseCode = 62, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = true, EffectiveDate = SetPractIdToMandatorySept6th2022, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Feb 2nd 2023
                    new LicenseDetail { Id =  203, LicenseCode = 32, Prefix = "R9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  204, LicenseCode = 33, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  205, LicenseCode = 34, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  206, LicenseCode = 35, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  207, LicenseCode = 36, Prefix = "R9", Manual = true, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  208, LicenseCode = 37, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  209, LicenseCode = 39, Prefix = "R9", Manual = false, Validate = true,  LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  210, LicenseCode = 40, Prefix = "R9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  211, LicenseCode = 43, Prefix = "Y9", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  212, LicenseCode = 46, Prefix = "Y9", Manual = false, Validate = false,  LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  213, LicenseCode = 49, Prefix = "96", Manual = true, Validate = false,  LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "NX", EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  214, LicenseCode = 52, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  215, LicenseCode = 53, Prefix = "L9", NamedInImReg = false, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  216, LicenseCode = 54, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  217, LicenseCode = 55, Prefix = "L9", NamedInImReg = true, LicensedToProvideCare = true, Manual = false, Validate = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  218, LicenseCode = 63, Prefix = "98", NamedInImReg = true, LicensedToProvideCare = false, Manual = true, Validate = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetPractIdToMandatoryFeb2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // March 15 2023 - set validate to true for nurses whenever PrescriberIdType is mandatory and validate set to false
                    new LicenseDetail { Id =  219, LicenseCode = 33, Prefix = "R9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  220, LicenseCode = 34, Prefix = "R9", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  221, LicenseCode = 35, Prefix = "R9", Manual = true, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  222, LicenseCode = 36, Prefix = "R9", Manual = true, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  223, LicenseCode = 37, Prefix = "R9", Manual = false, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  224, LicenseCode = 40, Prefix = "R9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  225, LicenseCode = 43, Prefix = "Y9", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  226, LicenseCode = 46, Prefix = "Y9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "YX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  227, LicenseCode = 49, Prefix = "96", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "NX", EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE},
                    new LicenseDetail { Id =  228, LicenseCode = 52, Prefix = "L9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  229, LicenseCode = 53, Prefix = "L9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  230, LicenseCode = 54, Prefix = "L9", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  231, LicenseCode = 55, Prefix = "L9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  232, LicenseCode = 63, Prefix = "98", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = PrescriberIdType.Mandatory, AllowRequestRemoteAccess = false, EffectiveDate = SetValidateForNurseMarch15th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    //BC College of Social Workers
                    new LicenseDetail { Id =  233, LicenseCode = 82, Prefix = "", Manual = true, Validate = false, LicensedToProvideCare = false, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = June9th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  234, LicenseCode = 83, Prefix = "", Manual = true, Validate = false, LicensedToProvideCare = false, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = June9th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  235, LicenseCode = 84, Prefix = "", Manual = true, Validate = false, LicensedToProvideCare = false, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = June9th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  236, LicenseCode = 85, Prefix = "", Manual = true, Validate = false, LicensedToProvideCare = false, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = June9th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id =  237, LicenseCode = 86, Prefix = "", Manual = true, Validate = false, LicensedToProvideCare = false, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = June9th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Adjustments to onboard College of Optometrists
                    new LicenseDetail { Id = 261, LicenseCode = 72, Prefix = "94", Manual = false, Validate = true, NamedInImReg = true,  LicensedToProvideCare = true, EffectiveDate = AdjustmentsToOnboardCollegeOfOptometristsAug2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 262, LicenseCode = 73, Prefix = "94", Manual = true, Validate = true, NamedInImReg = false,  LicensedToProvideCare = true, EffectiveDate = AdjustmentsToOnboardCollegeOfOptometristsAug2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 263, LicenseCode = 74, Prefix = "94", Manual = true, Validate = true, NamedInImReg = false,  LicensedToProvideCare = true, EffectiveDate = AdjustmentsToOnboardCollegeOfOptometristsAug2nd2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // CPSBC license classes changes
                    // New
                    new LicenseDetail { Id = 264, LicenseCode = 87, Prefix = "91", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 265, LicenseCode = 88, Prefix = "91", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 266, LicenseCode = 89, Prefix = "91", Manual = true, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    // `LicensedToProvideCare = false` so that OBO TOA will be assigned
                    new LicenseDetail { Id = 267, LicenseCode = 90, Prefix = "91", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    // `LicensedToProvideCare = false` so that OBO TOA will be assigned
                    new LicenseDetail { Id = 268, LicenseCode = 91, Prefix = "91", Manual = true, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    // Adjustments
                    new LicenseDetail { Id = 269, LicenseCode = 7, Prefix = "91", Manual = false, Validate = true, NamedInImReg = true, LicensedToProvideCare = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 270, LicenseCode = 9, Prefix = "91", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 271, LicenseCode = 15, Prefix = "91", Manual = false, Validate = true, NamedInImReg = true, LicensedToProvideCare = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 272, LicenseCode = 16, Prefix = "91", Manual = true, Validate = true, NamedInImReg = true, LicensedToProvideCare = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    new LicenseDetail { Id = 273, LicenseCode = 17, Prefix = "91", Manual = false, Validate = true, NamedInImReg = true, LicensedToProvideCare = true, PrescriberIdType = null, AllowRequestRemoteAccess = true, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                    // `LicensedToProvideCare = false` so that OBO TOA will be assigned
                    new LicenseDetail { Id = 274, LicenseCode = 22, Prefix = "91", Manual = false, Validate = true, LicensedToProvideCare = false, NamedInImReg = true, PrescriberIdType = null, AllowRequestRemoteAccess = false, EffectiveDate = AdjustmentsToCPSBCAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // Employed Student Nurse Change
                    new LicenseDetail { Id = 275, LicenseCode = 40, Prefix = "R9", Manual = false, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = PrescriberIdType.Optional, AllowRequestRemoteAccess = false, NonPrescribingPrefix = "RX", EffectiveDate = EmployedStudentNurseChangeAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },

                    // CPSBC - Physician Assistant
                    new LicenseDetail { Id = 276, LicenseCode = 92, Prefix = "M9", Manual = true, Validate = true, LicensedToProvideCare = true, NamedInImReg = false, PrescriberIdType = null, AllowRequestRemoteAccess = false, NonPrescribingPrefix = null, EffectiveDate = PhysicalAssistantChangeAug28th2023, CreatedTimeStamp = SEEDING_DATE, UpdatedTimeStamp = SEEDING_DATE },
                 };
            }
        }

        public override void Configure(EntityTypeBuilder<LicenseDetail> builder)
        {
            builder.HasOne(ld => ld.License)
                .WithMany(l => l.LicenseDetails)
                .HasForeignKey(cl => cl.LicenseCode);
            builder.HasData(SeedData);
        }
    }
}
