{{- if .Values.database.autoCreate }}
{{- $ocEnv := regexFind "([^-]*$)" .Release.Namespace -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prime-docman.fullname" . }}-createdb
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    {{- include "prime-docman.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: createdb
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - >
            createdb -O $(APPUSER) prime-{{ $ocEnv }} 2> /dev/null || echo "database already exists"
        env:
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: database-host
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: superuser-username
          - name: APPUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-password
          - name: PGDATABASE
            {{- if hasPrefix "pr-" .Release.Name }}
            value: {{ .Release.Name }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-name
            {{- end }}
        envFrom:
          - configMapRef:
              name: document-manager
      restartPolicy: Never
  backoffLimit: 3
{{- end }}