{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prime-docman.fullname" . }}-migrations
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "prime-docman.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo The pre-install hook Pod is running  - hook-preinstall && sleep 15']
      restartPolicy: Never
  backoffLimit: 3
{{- end }}