{{- if .Values.migrations.enabled }}
{{- $ocEnv := regexFind "([^-]*$)" .Release.Namespace -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prime-docman.fullname" . }}-migrations
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "prime-docman.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        command:
          - flask
          - db 
          - upgrade
          - '${FLASK_RUN_PARAMS}'
        env:
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: database-host
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: superuser-username
          - name: APPUSER
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-password
          - name: PGDATABASE
            {{- if hasPrefix "pr-" .Release.Name }}
            value: {{ .Release.Name }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: {{ $ocEnv }}-patroni-secret
                key: app-db-name
            {{- end }}
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDATABASE)"
        envFrom:
          - configMapRef:
              name: document-manager
      restartPolicy: Never
  backoffLimit: 3
{{- end }}