{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prime-docman.fullname" . }}
  labels:
    {{- include "prime-docman.labels" . | nindent 4 }}
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.persistence.volumeSize }}
{{- end }}
