export enum Province {
  ALBERTA = 'AB',
  BRITISH_COLUMBIA = 'BC',
  MANITOBA = 'MB',
  NEW_BRUNSWICK = 'NB',
  NEWFOUNDLAND_AND_LABRADOR = 'NL',
  NOVA_SCOTIA = 'NS',
  NORTHWEST_TERRITORIES = 'NT',
  NUNAVUT = 'NU',
  ONTARIO = 'ON',
  PRINCE_EDWARD_ISLAND = 'PE',
  QUEBEC = 'QC',
  SASKATCHEWAN = 'SK',
  YUKON = 'YT'
}
