version: "2"         # required to adjust maintainability checks
plugins:
  brakeman:
    enabled: false
  rubocop:
    enabled: false
  eslint:
    enabled: false

# Exclude Folder Pattern
# Exclude File Pattern
exclude_patterns:
  - "Migrations/"
  - "Controllers/"
  - "Views/"
  - "ViewModels/"
  - "Resrouces/"
  - "Configuration/"
  - "logs/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.spec.*"
  - "**/*.json"
  - "**/*.html"
  - "**/*.cshtml"
  - "**/*ViewModel.cs"
  - "**/*Designer.cs"
  - "Migrations/ApiDbContextModelSnapshot.cs"


# examples of minified files that should be excluded
# - **.min.js
# - **.min.css

