using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using Prime.HttpClients.DocumentManagerApiDefinitions;

namespace Prime.HttpClients
{
    public interface IDocumentManagerClient
    {
        /// <summary>
        /// Initializes the file upload process with the Document Manager.
        /// </summary>
        /// <param name="filename"></param>
        /// <param name="fileSize"></param>
        /// <returns></returns>
        Task<HttpResponseMessage> InitializeUploadAsync(string filename, string fileSize);

        /// <summary>
        /// Moves a temporary file upload to its final destination and marks it as "submitted".
        /// </summary>
        /// <returns>The file name; or null if not successful.</returns>
        Task<string> FinalizeUploadAsync(Guid documentGuid, string destinationFolder);

        /// <summary>
        /// Creates a short-lived, single use download token that can be used to download the Document directly from the Document Manager.
        /// </summary>
        /// <param name="documentGuid"></param>
        Task<string> CreateDownloadTokenAsync(Guid documentGuid);

        /// <summary>
        /// Uploads a file directly to the Document Manager, rather than using the regular chunked file upload process.
        /// Generally used to persist files generated by the PRIME API; not for user uploaded files.
        /// </summary>
        /// <param name="file"></param>
        /// <param name="filename"></param>
        /// <param name="destinationFolder"></param>
        /// <returns>The Document GUID returned from the Document Manager.</returns>
        Task<Guid> SendFileAsync(Stream file, string filename, string destinationFolder);

        /// <summary>
        /// Downloads a Document from the Document Manager.
        /// Generally only used when downloading a file without using the frontend, since this requires the file to be transferred to the API first and then again to the user.
        /// </summary>
        /// <param name="documentGuid"></param>
        /// <returns>The file as HttpContent, or null if unsuccessful.</returns>
        Task<HttpContent> GetDocumentAsync(Guid documentGuid);
    }
}
