apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mailhog
  name: mailhog
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  - name: "25"
    port: 25
    targetPort: 1025
  - name: "80"
    port: 80
    targetPort: 8025
  selector:
    io.kompose.service: mailhog
status:
  loadBalancer: {}
