apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sonarrunner
  name: sonarrunner
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: sonarrunner
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
