---
# From https://github.com/bcgov/nr-showcase-devops-tools/blob/master/tools/jenkins/openshift/ns-config.yaml
kind: Template
apiVersion: v1
labels:
  app: jenkins-prod
metadata:
  name: jenkins
objects:
- apiVersion: v1
  data:
    project.dev: "${DEV}"
    project.test: "${TEST}"
    project.prod: "${PROD}"
    project.tools: "${TOOLS}"
  kind: ConfigMap
  metadata:
    name: ns-config
parameters:
- name: DEV
  displayName: Dev Project Namespace
  description: Project/Namespace for Dev. Environment
  required: true
  value: dev
- name: TEST
  displayName: Test Project Namespace
  description: Project/Namespace for Test Environment
  required: true
  value: test
- name: PROD
  displayName: Prod Project Namespace
  description: Project/Namespace for Prod. Environment
  required: true
  value: prod
- name: TOOLS
  displayName: Tools Project Namespace
  description: Project/Namespace for Tools Environment
  required: true
  value: tools