---
# From https://github.com/bcgov/nr-showcase-devops-tools/blob/master/tools/jenkins/openshift/secrets.yaml
kind: Template
apiVersion: v1
labels:
  app: jenkins-prod
metadata:
  name: jenkins
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: template.${NAME}-slave-user
  stringData:
    metadata.name: template.${NAME}-slave-user
    username: jenkins-slave
- apiVersion: v1
  kind: Secret
  metadata:
    name: template.${NAME}-github
  stringData:
    metadata.name: template.${NAME}-github
    username: "${GH_USERNAME}"
    password: "${GH_PASSWORD}"
parameters:
- name: NAME
  displayName: Name
  description: A name used for all objects
  required: true
  value: jenkins
- name: GH_USERNAME
  required: true
- name: GH_PASSWORD
  description: GitHub Personal Access Token
  required: true