export enum BusinessEventTypeEnum {
  STATUS_CHANGE_CODE = 1,
  EMAIL_CODE,
  NOTE_CODE,
  ADMIN_ACTION_CODE,
  ENROLLEE_CODE,
  SITE_CODE,
  ADMIN_VIEW_CODE,
  ORGANIZATION_CODE,
  PHARMANET_API_CALL_CODE,
  PAPER_ENROLMENT_LINK_CODE,
}
