export enum EmailTemplateTypeEnum {
  ENROLLEE_STATUS_CHANGE = 1,
  COMMUNITY_PRACTICE_NOTIFICATION,
  COMMUNITY_PHARMACY_NOTIFICATION,
  HEALTH_AUTHORITY_NOTIFICATION,
  REMOTE_USER_NOTIFICATION,
  REMOTE_USER_UPDATED_NOTIFICATION,
  HIBC_SITE_SUBMISSION,
  ENROLLEE_RENEWAL_REQUIRED,
  BUSINESS_LICENCE_UPLOAD,
  ENROLLEE_RENEWAL_PASSED,
  SITE_APPROVED_PHARMANET_ADMINISTRATOR,
  SITE_APPROVED_SIGNING_AUTHORITY,
  SITE_REGISTRATION_SUBMISSION,
  ORGANIZATION_CLAIM_APPROVAL_NOTIFICATION,
  SITE_REVIEWED_NOTIFICATION
}
