kind: Template
apiVersion: v1
metadata:
  name: "${BUILDER_IMAGE_NAME}"
  creationTimestamp: null
  annotations:
    tags: "builder,nodejs,yarn"
    iconClass: icon-nodejs
    description: >-
      This template defines resources needed to build Angular frontend
      applications. This is your builder image that compiles the Angular source
      code. This builder image uses YARN instead of NPM to build the frontend.
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${BUILDER_IMAGE_NAME}"
      annotations:
        description: Keeps track of changes in this builder image.
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${BUILDER_IMAGE_NAME}"
      creationTimestamp: null
      annotations:
        description: Defines how to build Angular applications from source code.
    spec:
      runPolicy: Serial
      triggers:
        - type: ConfigChange
        - type: ImageChange
      source:
        type: Git
        git:
          ref: "${GIT_REF}"
          uri: "${GIT_REPO_URL}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: openshift.dockerfile
          env:
            - name: SUFFIX
              value: "${SUFFIX}"
            - name: REDIRECT_URL
              value: "${REDIRECT_URL}"
            - name: OC_APP
              value: ${OC_APP}
            
            # Document Manager related environment variables
            - name: DOCUMENT_MANAGER_URL
              value: "https://${VANITY_URL}/api/docman"

            # Keycloak related environment variables
            - name: JWT_WELL_KNOWN_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: "keycloak"
                  key: jwt_well_known_config                
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: "keycloak"
                  key: keycloak_client_id                
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: "keycloak"
                  key: keycloak_realm                
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: "keycloak"
                  key: keycloak_url
      output:
        to:
          kind: ImageStreamTag
          name: "${BUILDER_IMAGE_NAME}:latest"
      resources: {}
      postCommit: {}
    status:
      lastVersion: 0
parameters:
  - name: BUILDER_IMAGE_NAME
    displayName: Builder Image
    description: >-
      The name assigned to the builder image defined in this template. You
      should keep this as default unless you know what you are doing.
    required: true
    value: angular-frontend-develop-temp-ocp4
  - name: GIT_REPO_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: "https://github.com/bcgov/moh-prime.git"
  - name: GIT_REF
    displayName: Git Reference
    description: >-
      Set this to a branch name, tag or other ref of your repository if you are
      not using the default branch.
    required: true
    value: "feature/prime-1195-1197-ocp4-jenkins"
  - name: SOURCE_CONTEXT_DIR
    displayName: Context Directory
    description: >-
      Set this to the relative path to the Dockerfile that describes this
      builder image, if it is not in the root of your repository.
    required: true
    # value: openshift/templates/builder/