---
apiVersion: v1
kind: Template
metadata:
  name: document-manager-bc
  creationTimestamp: null
  description: >-
    Build configuration template for PRIME's Document Manager component.
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: false
    value: latest
  - name: SOURCE_CONTEXT_DIR
    value: document-manager/backend
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/moh-prime
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
    value: 9c33a9
  - name: OC_APP
    required: true
    value: dev
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: '${NAME}${SUFFIX}'
    creationTimestamp: null
    labels:
      shared: 'true'
    annotations:
      description: Keeps track of changes in the application image
  spec:
    lookupPolicy:
      local: false
    tags: []

# Document Manager - Build Configuration
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: '${NAME}${SUFFIX}'
    creationTimestamp: null
    annotations:
      description: Defines how to build the application
  spec:
    completionDeadlineSeconds: 6000
    triggers:
      - type: ImageChange
      - type: ConfigChange
    runPolicy: SerialLatestOnly
    source:
      type: Git
      git:
        uri: '${SOURCE_REPOSITORY_URL}'
        ref: '${SOURCE_REPOSITORY_REF}'
      contextDir: '${SOURCE_CONTEXT_DIR}'
    strategy:
      dockerStrategy:
        noCache: true
        dockerfilePath: openshift.dockerfile
        env:
          - name: SUFFIX
            value: ${SUFFIX}
          - name: BUILD_LOGLEVEL
            value: '2'
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: '${NAME}${SUFFIX}:latest'
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    nodeSelector: null
