---
apiVersion: v1
kind: Template
labels:
  template: mailhog-server
metadata:
  creationTimestamp: null
  name: -mailhog-server-dc
  description: >-
    Deployment configuration template for Mailhog, a service used to capture 
    emails sent out in development and test environments only.
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: '9c33a9'
  - name: OC_APP
    required: true
    value: 'tools'
objects:
  # Mailhog service (endpoint for internal routing to related pods)
  - kind: Service
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      ports:
      - name: "1025"
        port: 1025
        targetPort: 1025
      - name: "25"
        port: 25
        targetPort: 1025
      - name: "80"
        port: 80
        targetPort: 8025
      selector:
        io.kompose.service: mailhog-server
    status:
      loadBalancer: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      tags:
      - annotations: null
        from:
          kind: ImageStreamTag
          name: mailhog:latest
        generation: null
        importPolicy: {}
        name: latest
    status:
      dockerImageRepository: ""
  
  # Mailhog - Deployment configuration
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      replicas: 1
      selector:
        io.kompose.service: mailhog-server
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: mailhog-server
        spec:
          containers:
          - image: ' '
            name: mailhog-server
            ports:
            - containerPort: 1025
            - containerPort: 1025
            - containerPort: 8025
            resources: {}
          restartPolicy: Always
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - mailhog-server
          from:
            kind: ImageStreamTag
            name: mailhog:latest
        type: ImageChange
    status: {}

