---
apiVersion: v1
kind: Template
metadata:
  name: schemaspy-bc
  annotations:
    description: SchemaSpy build template.
    tags: schema-spy
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: '9c33a9'
  - name: OC_APP
    required: true
    value: 'tools'
  - name: SOURCE_CONTEXT_DIR
    required: false
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "schemaspy"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "schemaspy"
      labels:
        app: "schemaspy"
        buildconfig: "schemaspy"
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "schemaspy"
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "schemaspy:latest"
      triggers:
      - type: ConfigChange
      - type: ImageChange
