apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab-runner
  name: gitlab-runner
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gitlab-runner
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
