apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab-runner
  name: gitlab-runner
spec:
  replicas: 1
  selector:
    io.kompose.service: gitlab-runner
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gitlab-runner
    spec:
      containers:
      - image: ' '
        name: gitlab-runner
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-runner
      from:
        kind: ImageStreamTag
        name: gitlab-runner:latest
    type: ImageChange
status: {}
