# Based on update-email-statuses.cron.yml
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for job that activates api to update email statuses
    tags: cronjob
  name: update-email-statuses-cronjob-template
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: '${CRON_NAME}'
    spec:
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - command:
                  - bash
                  - '-c'
                  - >-
                    echo -e "-------- STARTING CRON --------\n"

                    echo -e "-------- Getting access_token --------\n"

                    TOKEN=$(curl -X POST
                    "${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token"
                    \
                      -H "Content-Type: application/x-www-form-urlencoded" \
                      -d "grant_type=client_credentials" \
                      -d "client_id=${KEYCLOAK_CLIENT_ID}" \
                      -d "client_secret=${KEYCLOAK_CLIENT_SECRET}" | python -c "import sys, json; print json.load(sys.stdin)['access_token']")

                    echo -e ${TOKEN}

                    echo -e "-------- Calling PRIME API --------\n"

                    curl -v -X POST
                    http://dotnet-webapi${SUFFIX}:8080/api/Emails/management/statuses
                    \
                      -H "Authorization: Bearer ${TOKEN}" \
                      -H "Content-Length: 0"

                    echo -e "-------- CRON COMPLETE --------\n"
                  env:
                    - name: KEYCLOAK_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: prime_service_account_client_secret
                          name: prime-service-account
                    - name: KEYCLOAK_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          key: prime_service_account_client_id
                          name: prime-service-account
                    - name: KEYCLOAK_URL
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_URL
                          name: keycloak
                    - name: KEYCLOAK_REALM
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_REALM
                          name: keycloak
                  image: >-
                    docker-registry.default.svc:5000/openshift/base-centos7:latest
                  limits:
                    cpu: 500m
                    memory: 2Gi
                  name: '${CRON_NAME}'
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  resources: null
              restartPolicy: Never
      schedule: '${CRON_SCHEDULE}'
parameters:
  - description: 'Cron-like schedule expression. Default: At minute 0 past every 6th hour.'
    name: CRON_SCHEDULE
    value: '0 */6 * * *'
  - name: CRON_NAME
    value: update-email-statuses-cronjob
  - description: 'Environment name suffix appended to all OpenShift objects'
    name: SUFFIX
    required: false
