---
# From https://github.com/bcgov/nr-showcase-devops-tools/blob/master/tools/jenkins/openshift/jobs-config.yaml
kind: Template
apiVersion: v1
labels:
  app: jenkins-prod
metadata:
  name: jenkins
objects:
- apiVersion: v1
  data:
    app.name: "${APP_NAME}"
    app.domain: "${APP_DOMAIN}"
    repo.name: "${REPO_NAME}"
    repo.owner: "${REPO_OWNER}"
  kind: ConfigMap
  metadata:
    name: jobs-config
parameters:
- name: REPO_OWNER
  displayName: Application Repository Owner
  description: A name of the github repo owner
  required: true
  value: bcgov
- name: REPO_NAME
  displayName: Application Repository Name
  description: Name of the application repository (code to build)
  required: true
- name: APP_NAME
  description: Short name (one word, lowercase) of the application
  required: true
- name: APP_DOMAIN
  description: Internet domain for the application
  required: true
  value: pathfinder.gov.bc.ca