apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prime
  description: >-
    Deployment template for the Ministry of Health PharmaNet Revisions for Information Management Enhancements
parameters:
- name: SVC_NAME
  displayName: Name
  description: A name appended to all objects
  required: true
  value: prime
- name: IMAGE_TAG
  displayName: Image Tag
  description: an identifier that labels which version an image belongs to.
  required: true
- name: OC_LICENSE_PLATE
  displayName: OpenShift License Plate
  description: Prepends your dev/test/prod URL
  required: true
  value: 9c33a9
- name: OC_ENV
  displayName: Openshift Environment
  description: dev/test/prod
  required: true
- name: FRONTEND_REPLICAS
  displayName: Number of frontend pods
  description: For scaling frontend pods
  required: true
  value: '3'
- name: BACKEND_REPLICAS
  displayName: Number of backend pods
  description: For scaling backend pods
  required: true
  value: '3'
- name: VANITY_URL
  displayName: Vanity URL
  description: Minus the HTTP/HTTPS, this is your vanity URL or the prefix of your default URL
  required: true
  value: vanity
- name: ASP_ENV
  displayName: ASP.NET Environment
  description: Development or Production
  required: true
  value: Development
- name: DOCMAN_VOLUME_CAPACITY
  displayName: Document Manager Persistent Volume Capacity
  description: Volume space available for Document Manager Backend data e.g. 512Mi, 2Gi.
  required: true
  value: 5Gi
- name: WEB_PORT
  displayName: Web Port for NGINX
  description: Termination port on NGINX (8080 or 8443)
  value: "8080"
- name: URL_STUB
  displayName: URL Stub
  description: Appended to all URLs, used in PRs
  value: "-9c33a9-dev.apps.silver.devops.gov.bc.ca"
  required: false
- name: HPR_URL
  displayName: Health Practicioner URL
  value: ""
- name: MAUTH_URL
  displayName: MUTUAL_AUTHENTICATION URL
  value: ""
- name: CRON_SCHEDULE_RENEWALS
  description: 'Renewal email sending cron schedule. Cron-like schedule expression. Default: Once a day at 11 PM'
  value: '0 23 * * *'
- name: CRON_SCHEDULE_STATUSES
  description: 'Email status update cron job. Cron-like schedule expression. Default: At minute 0 past every 6th hour.'
  value: '0 */6 * * *'
objects:
###########################################
###               Frontend              ###
###########################################
#   Frontend Deployment Config
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: ${SVC_NAME}-frontend
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
      app.openshift.io/runtime: nginx
  spec:
    completionDeadlineSeconds: 1200
    replicas: ${{FRONTEND_REPLICAS}}
    selector:
      name: ${SVC_NAME}-frontend
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 120
        maxSurge: "20%"
        maxUnavailable: "10%"
    template:
      metadata:
        labels:
          dev-app: ${SVC_NAME}
          name: ${SVC_NAME}-frontend
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                  - key: deploymentconfig
                    operator: In
                    values:
                    - ${SVC_NAME}-frontend
        volumes:
        - name: vanity-tls-certs
          secret:
            secretName: vanity-tls-certificate
            defaultMode: 420
        - name: nginx-config
          configMap:
            name: ${SVC_NAME}-nginx-config
            defaultMode: 420
        - name: plr-integration-volume
          secret:
            secretName: plr-integration
            defaultMode: 420
        - name: env-config
          configMap:
            name: ${SVC_NAME}-env-config
            defaultMode: 420
        containers:
        - name: ${SVC_NAME}-frontend
          image: >-
            image-registry.openshift-image-registry.svc:5000/${OC_LICENSE_PLATE}-tools/prime-frontend:${IMAGE_TAG}
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
          - containerPort: 8890
            protocol: TCP
          volumeMounts:
          - name: vanity-tls-certs
            readOnly: true
            mountPath: /opt/bitnami/nginx/conf/certs
          - name: plr-integration-volume
            readOnly: true
            mountPath: /opt/bitnami/nginx/conf/certs/plr
          - name: nginx-config
            readOnly: true
            mountPath: /opt/bitnami/nginx/conf/nginx.conf
            subPath: nginx.conf
          - name: env-config
            readOnly: true
            mountPath: /opt/app-root/src/assets/config-map.json
            subPath: config-map.json
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 15m
              memory: 10Mi
          envFrom:
          - configMapRef:
              name: keycloak
          env:
          - name: DOCUMENT_MANAGER_URL
            value: https://${VANITY_URL}/api/docman
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${SVC_NAME}-frontend
        from:
          kind: ImageStreamTag
          namespace: "${OC_LICENSE_PLATE}-tools"
          name: 'prime-frontend:${IMAGE_TAG}'

#   NGINX Configuration
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SVC_NAME}-nginx-config
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
  data:
    nginx.conf: |-
      # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
      #user              www www;  ## Default: nobody

      worker_processes  auto;
      error_log         "/opt/bitnami/nginx/logs/error.log";
      pid               "/opt/bitnami/nginx/tmp/nginx.pid";

      events {
          worker_connections  1024;
      }

      http {
          include       mime.types;
          default_type  application/octet-stream;
          log_format    main '$remote_addr - $remote_user [$time_local] '
                            '"$request" $status  $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';
          access_log    "/opt/bitnami/nginx/logs/access.log" main;
          # add_header    X-Frame-Options SAMEORIGIN;

          client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
          proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
          fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
          scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
          uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

          sendfile           on;
          # tcp_nopush         on;
          tcp_nodelay        off;
          gzip               on;
          gzip_http_version  1.0;
          gzip_comp_level    2;
          gzip_proxied       any;
          gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
          keepalive_timeout  65;
          ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
          ssl_ciphers        HIGH:!aNULL:!MD5;
          client_max_body_size 80M;
          server_tokens off;

        server {
          listen 8080;
          server_name localhost *.gov.bc.ca;
          server_tokens off;

          root /opt/app-root/src;
          index index.html index.htm;

          include mime.types;
          add_header X-Frame-Options "ALLOW-FROM common-logon-dev.hlth.gov.bc.ca" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header Content-Security-Policy "frame-ancestors 'self'  common-logon-dev.hlth.gov.bc.ca; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://fonts.gstatic.com ; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com" always;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header Referrer-Policy "no-referrer-when-downgrade";

          gzip on;
          gzip_min_length 1000;
          gzip_proxied expired no-cache no-store private auth;
          gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

          location / {
            try_files $uri $uri/ /index.html$args;
          }
          location /api/docman/ {
            proxy_pass http://${SVC_NAME}-document-manager:6001/;
          }
          location /api/v1/ {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/;
          }
          location /api/v1/PLRHL7 {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/PLRHL7;
            #        proxy_set_header  X-SSL-CERT $ssl_client_escaped_cert;
          }
          location /nginx_status {
            # Enable Nginx stats
            stub_status on;
            # Only allow access from localhost
            allow 127.0.0.1;
            # Other request should be denied
            deny all;
            # No need to log this request, its just noise
            access_log on;
          }
        }
        server {
          listen 8443 ssl;
          server_name *.gov.bc.ca;
          ssl_password_file certs/passwd.txt;
          ssl_certificate certs/chained.crt;
          ssl_certificate_key certs/private.key;
          server_tokens off;
          #    ssl_verify_client   optional_no_ca;

          root /opt/app-root/src;
          index index.html index.htm;

          add_header X-Frame-Options "ALLOW-FROM common-logon-dev.hlth.gov.bc.ca" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header Content-Security-Policy "frame-ancestors 'self'  common-logon-dev.hlth.gov.bc.ca; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://fonts.gstatic.com ; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com" always;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header Referrer-Policy "no-referrer-when-downgrade";

          gzip on;
          gzip_min_length 1000;
          gzip_proxied expired no-cache no-store private auth;
          gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

          location / {
            try_files $uri $uri/ /index.html$args;
          }
          location /api/docman/ {
            proxy_pass http://${SVC_NAME}-document-manager:6001/;
          }
          location /api/v1/ {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/;
          }
          location /api/v1/PLRHL7 {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/PLRHL7;
            #        proxy_set_header  X-SSL-CERT $ssl_client_escaped_cert;
          }
          location /nginx_status {
            # Enable Nginx stats
            stub_status on;

            # Only allow access from localhost
            allow 127.0.0.1;

            # Other request should be denied
            deny all;

            # No need to log this request, its just noise
            access_log on;
          }
        }
        server {
          listen 8888;
          server_name *.gov.bc.ca;
          server_tokens off;

          root /opt/app-root/src;
          index index.html index.htm;

          add_header X-Frame-Options "ALLOW-FROM common-logon-dev.hlth.gov.bc.ca" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header Content-Security-Policy "frame-ancestors 'self'  common-logon-dev.hlth.gov.bc.ca; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://fonts.gstatic.com ; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com" always;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header Referrer-Policy "no-referrer-when-downgrade";
          gzip on;
          gzip_min_length 1000;
          gzip_proxied expired no-cache no-store private auth;
          gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

          location / {
            try_files $uri $uri/ /index.html$args;
          }
          location /api/docman/ {
            proxy_pass http://${SVC_NAME}-document-manager:6001;
          }
          location /api/v1/ {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/;
          }
          location /nginx_status {
            # Enable Nginx stats
            stub_status on;
            # Only allow access from localhost
            allow 127.0.0.1;
            # Other request should be denied
            deny all;
            # No need to log this request, its just noise
            access_log on;
          }
        }
        server {
          # Block for API end-points that require a client certificate (Multual Authentication)
          listen 8890 ssl;
          server_name *.gov.bc.ca;
          ssl_password_file certs/passwd.txt;
          ssl_certificate certs/chained.crt;
          ssl_certificate_key certs/private.key;
          server_tokens off;
          ssl_verify_client optional_no_ca;
          ssl_client_certificate certs/plr/trusted-ca-certs.pem;
          root /opt/app-root/src;
          index index.html index.htm;

          # add_header X-Frame-Options "ALLOW-FROM common-logon-dev.hlth.gov.bc.ca" always;
          # add_header X-XSS-Protection "1; mode=block" always;
          # add_header Content-Security-Policy "frame-ancestors 'self'  common-logon-dev.hlth.gov.bc.ca; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://fonts.gstatic.com ; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com" always;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
          add_header X-Content-Type-Options "nosniff" always;
          # add_header Referrer-Policy "no-referrer-when-downgrade";
          gzip on;
          gzip_min_length 1000;
          gzip_proxied expired no-cache no-store private auth;
          gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

          location /api/v1/PLRHL7 {
            proxy_pass http://${SVC_NAME}-webapi:8080/api/PLRHL7;
            proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
          }
        }
      }

- apiVersion: v1
  #   Frontend Service
  kind: Service
  metadata:
    name: ${SVC_NAME}-frontend
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "https"
      port: 8443
      targetPort: 8443
    - name: "hpr"
      port: 8888
      targetPort: 8888
    - name: "mutualauth"
      port: 8890
      targetPort: 8890
    selector:
      name: ${SVC_NAME}-frontend
- kind: Route
  #   Frontend Route (Web)
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${SVC_NAME}-frontend
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
  spec:
    host: ${SVC_NAME}${URL_STUB}
    to:
      kind: Service
      name: ${SVC_NAME}-frontend
      weight: 100
    port:
      targetPort: http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

#   Frontend Route (Health Practitioner Registration)
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${SVC_NAME}-frontend-hpr
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
  spec:
    host: ${HPR_URL}
    to:
      kind: Service
      name: ${SVC_NAME}-frontend
      weight: 100
    port:
      targetPort: 8888
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  #   Frontend Route (Mutual Authentication)
  kind: Route
  metadata:
    name: ${SVC_NAME}-frontend-mutualauth
    namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
    labels:
      app.kubernetes.io/part-of: ${SVC_NAME}
  spec:
    host: ${MAUTH_URL}
    to:
      kind: Service
      name: ${SVC_NAME}-frontend
      weight: 100
    port:
      targetPort: 8890
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
