apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-fluentbit-config
  namespace: ${OC_LICENSE_PLATE}-${OC_ENV}
  labels: 
    app.kubernetes.io/part-of: dev
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush         5
      Daemon        Off
      # define the log format (see additional config map key/value)
      Parsers_File  parsers.conf
      Log_Level     info
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020
      Health_Check  On

    [INPUT]
      # get logs from file written by nginx app (eg: dev-webapi)
      Name        tail
      Path        /opt/app-root/app/logs/*.log
      Tag         app

    [FILTER]
      name          parser
      match         app
      Key_Name      log
      Parser        json
      Reserve_Data  On
      Preserve_Key  On
    
    [FILTER]
      # modify log entry to include more key/value pairs
      name    record_modifier
      match   app
      # add namespace
      Record  namespace ${OC_LICENSE_PLATE}-${OC_ENV}
      # add pod name
      Record  product ${OC_ENV}-webapi

    [FILTER]
      Name          rewrite_tag
      Match         app
      Rule          $level ([a-zA-Z]*)$ $TAG.$level true
      Emitter_Name  re_emitted

    [FILTER]
      name   grep
      match  app
      regex  log ERR

    [OUTPUT]
      name                 slack
      match                app
      webhook              ${SLACK_WEBHOOK}

    [OUTPUT]
      Name    stdout
      Match   app
      Format  json_lines

  parsers.conf: |
    [PARSER]
      Name             json
      Format           json
      Decode_Field_as  escaped_utf8 log do_next
      Decode_Field_as  json log
