---
apiVersion: v1
kind: Template
metadata:
  name: angular-frontend-dc
  creationTimestamp:
  description: >-
    Deployment configuration template for PRIME's Angular frontend component.
parameters:
- name: NAME
  displayName: Name
  description: A prefix appended to all objects
  required: true
- name: SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: false
- name: VERSION
  required: true
- name: SOURCE_CONTEXT_DIR
  required: true
- name: SOURCE_REPOSITORY_URL
  required: true
- name: SOURCE_REPOSITORY_REF
  required: true
- name: OC_NAMESPACE
  required: true
- name: OC_APP
  required: true
- name: VANITY_URL
  required: true
  value: "pharmanetenrolment.gov.bc.ca"
- name: HTTP_SCHEMA
  required: true
  value: "https"
- name: HTTP_PORT
  required: true
  value: "8443"
- name: TERMINATION_TYPE
  required: true
  value: "Passthrough"
- name: REDIRECT_URL
  required: true
  value: "https://pharmanetenrolment.gov.bc.ca"
objects:

# Frontend deployment configuration
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/bcgov/moh-prime.git
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp:
    labels:
      io.kompose.service: "${NAME}${SUFFIX}"
    name: "${NAME}${SUFFIX}"
  spec:
    completionDeadlineSeconds: 1200
    replicas: 1
    selector:
      io.kompose.service: "${NAME}${SUFFIX}"
    strategy:
    template:
      metadata:
        creationTimestamp:
        labels:
          io.kompose.service: "${NAME}${SUFFIX}"
      spec:
        containers:
        - env:
          - name: SUFFIX
            value: "${SUFFIX}"
          - name: OC_APP
            value: ${OC_APP}
          - name: REDIRECT_URL
            value: "${REDIRECT_URL}"
          - name: DOCUMENT_MANAGER_URL
            value: "https://${VANITY_URL}/api/docman"
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_CLIENT_ID
                name: "keycloak"
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_REALM
                name: "keycloak"
          - name: KEYCLOAK_URL
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_URL
                name: "keycloak"
          image: " "
          name: primeweb
          ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 8888
          - containerPort: 8890
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/nginx/certs
              name: vanity-tls-certs
              readOnly: true
            - mountPath: /etc/nginx/certs/plr
              name: plr-integration-volume
              readOnly: true
        volumes:
          - name: vanity-tls-certs
            secret:
              defaultMode: 420
              secretName: vanity-tls-certificate
          - name: plr-integration-volume
            secret:
              defaultMode: 420
              secretName: plr-integration
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - primeweb
          from:
            kind: ImageStreamTag
            name: "${NAME}${SUFFIX}:latest"
        type: ImageChange
  status: {}

# Route definition to direct external traffic via Pharmanet Enrolment URL
- apiVersion: v1
  kind: Route
  metadata:
    name: "${NAME}${SUFFIX}"
  spec:
    host: "${VANITY_URL}"
    port:
      targetPort: "${HTTP_PORT}"
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: passthrough
    to:
      kind: Service
      name: "${NAME}${SUFFIX}"

# Route definition to direct external traffic via PHSA eForms URL
- apiVersion: v1
  kind: Route
  metadata:
    name: "${NAME}${SUFFIX}-hrp"
  spec:
    host: "healthpractionerregistration${SUFFIX}.pathfinder.gov.bc.ca"
    port:
      targetPort: "8888"
    tls:
        insecureEdgeTerminationPolicy: Allow
        termination: edge
    to:
      kind: Service
      name: "${NAME}${SUFFIX}"

# Angular service (endpoint definition for internal routing to related pods)
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp:
    labels:
      io.kompose.service: "${NAME}${SUFFIX}"
    name: "${NAME}${SUFFIX}"
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "8890"
      port: 8890
      targetPort: 8890
    selector:
      io.kompose.service: "${NAME}${SUFFIX}"
  status:
    loadBalancer: {}
