---
kind: Template
apiVersion: v1
metadata:
  name: angular-frontend-bc
  creationTimestamp: 
parameters:
- name: NAME
  displayName: Name
  description: A prefix appended to all objects
  required: true
- name: SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: false
- name: VERSION
  required: true
- name: SOURCE_CONTEXT_DIR
  required: true
- name: SOURCE_REPOSITORY_URL
  required: true
- name: SOURCE_REPOSITORY_REF
  required: true
- name: OC_NAMESPACE
  required: true
- name: OC_APP
  required: true
- name: VANITY_URL
  required: true
  value: 'pharmanetenrolment.gov.bc.ca'
- name: HTTP_SCHEMA
  required: true
  value: 'HTTPS'
- name: HTTP_PORT
  required: true
  value: '8443'
- name: TERMINATION_TYPE
  required: true
  value: 'passthrough'
- name: REDIRECT_URL
  required: true
  value: "https://pharmanetenrolment.gov.bc.ca"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: 
    labels:
      io.kompose.service: "${NAME}${SUFFIX}"
    name: "${NAME}${SUFFIX}"
  spec:
    containers:
    - env:
      - name: SUFFIX
        value: "${SUFFIX}"
      - name: REDIRECT_URL
        value: "${REDIRECT_URL}"
      - name: OC_APP
        value: ${OC_APP}
      - name: KEYCLOAK_CLIENT_ID
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_CLIENT_ID
            name: "keycloak"
      - name: KEYCLOAK_REALM
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_REALM
            name: "keycloak"
      - name: KEYCLOAK_URL
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_URL
            name: "keycloak"
      - name: JWT_WELL_KNOWN_CONFIG
        valueFrom:
          secretKeyRef:
            key: JWT_WELL_KNOWN_CONFIG
            name: 'keycloak'
    tags:
    - annotations: 
      from:
        kind: DockerImage
        name: "${NAME}${SUFFIX}"
      generation: 
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ''
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/bcgov/moh-prime.git
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: 
    labels:
      io.kompose.service: "${NAME}${SUFFIX}"
    name: "${NAME}${SUFFIX}"
  spec:
    dockerStrategy: 
      dockerfilePath: openshift.dockerfile
      env:
      - name: SUFFIX
        value: "${SUFFIX}"
      - name: REDIRECT_URL
        value: "${REDIRECT_URL}"
      - name: OC_APP
        value: ${OC_APP}
      - name: KEYCLOAK_CLIENT_ID
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_CLIENT_ID
            name: "keycloak"
      - name: KEYCLOAK_REALM
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_REALM
            name: "keycloak"
      - name: KEYCLOAK_URL
        valueFrom:
          secretKeyRef:
            key: KEYCLOAK_URL
            name: "keycloak"
      - name: JWT_WELL_KNOWN_CONFIG
        valueFrom:
          secretKeyRef:
            key: JWT_WELL_KNOWN_CONFIG
            name: 'keycloak'
    completionDeadlineSeconds: 6000
    nodeSelector: 
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}${SUFFIX}:latest"
    postCommit: {}
    resources:
      requests:
        cpu: '1'
        memory: 1Gi
      limits:
        cpu: '2'
        memory: 4Gi
    runPolicy: Serial
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      dockerStrategy: 
        dockerfilePath: openshift.dockerfile
        env:
          - name: SUFFIX
            value: "${SUFFIX}"
          - name: REDIRECT_URL
            value: "${REDIRECT_URL}"
          - name: OC_APP
            value: ${OC_APP}
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_CLIENT_ID
                name: "keycloak"
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_REALM
                name: "keycloak"
          - name: KEYCLOAK_URL
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_URL
                name: "keycloak"
          - name: JWT_WELL_KNOWN_CONFIG
            valueFrom:
              secretKeyRef:
                key: JWT_WELL_KNOWN_CONFIG
                name: 'keycloak'
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
  status:
    lastVersion: 0