apiVersion: v1
kind: Template
labels:
  template: database-backup-template
metadata:
  creationTimestamp: null
  name: database-backup-dc
parameters:
- name: NAME
  displayName: Name
  description: A prefix appended to all objects
  required: true
  value: backup
- name: SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: false
- name: VERSION
  required: false
- name: SOURCE_CONTEXT_DIR
  required: true
- name: SOURCE_REPOSITORY_URL
  required: true
- name: SOURCE_REPOSITORY_REF
  required: true
- name: OC_NAMESPACE
  required: true
- name: OC_APP
  required: true
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        io.kompose.service: ${NAME}
      strategy:
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.network/primenet: "true"
            io.kompose.service: ${NAME}
        spec:
          containers:
          - image: ' '
            name: ${NAME}
            ports:
            - containerPort: 5432
            resources: {}
            volumeMounts:
            - mountPath: /opt/backup
              name: backup-postgres-data
            - mountPath: /var/lib/postgresql/data
              name: postgresql
          restartPolicy: Always
          volumes:
          - name: backup-postgres-data
            persistentVolumeClaim:
              claimName: backup
          - name: postgresql
            persistentVolumeClaim:
              claimName: postresql
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - backup
          from:
            kind: ImageStreamTag
            name: backup:latest
        type: ImageChange
    status: {}
    