kind: Template
apiVersion: v1
metadata:
  name: document-manager-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: false
    value: latest
  - name: SOURCE_CONTEXT_DIR
    value: prime-database-backup
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/moh-prime
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
    value: dqszvc
  - name: OC_APP
    required: true
    value: dev
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: rhscl-python-36-rhel7
      creationTimestamp: 
      annotations:
        description: Python Base Image
      labels:
        shared: 'true'
    spec:
      lookupPolicy:
        local: false
      tags:
      - name: 3.6.1-36
        annotations: 
        from:
          kind: DockerImage
          name: registry.access.redhat.com/rhscl/python-36-rhel7:1-36
        importPolicy: {}
        referencePolicy:
          type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}-base"
      creationTimestamp: 
      annotations:
        description: Python Runtime Image
      labels:
        shared: 'true'
    spec:
      lookupPolicy:
        local: false
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
      creationTimestamp: 
      labels:
        shared: 'true'
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}-base"
    spec:
      completionDeadlineSeconds: 1440
      triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        contextDir: openshift/docker-images/python-36-docman
        type: Binary
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: rhscl-python-36-rhel7:3.6.1-36
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}${SUFFIX}-base"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
      creationTimestamp: 
      annotations:
        description: Defines how to build the application
    spec:
      completionDeadlineSeconds: 600
      triggers:
      - type: ImageChange
      - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "${NAME}${SUFFIX}-base"
          env:
          - name: BUILD_LOGLEVEL
            value: '2'
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}${SUFFIX}:${VERSION}"
      