kind: Template
apiVersion: v1
metadata:
  name: document-manager-base-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
    value: document-manager-base
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: false
    value: latest
  - name: SOURCE_CONTEXT_DIR
    value: document-manager
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/moh-prime
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
    value: dqszvc
  - name: OC_APP
    required: true
    value: dev
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhscl-python-36-rhel7
    creationTimestamp: null
    annotations:
      description: Python Base Image
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: false
    tags:
      - name: 3.6.1-36
        annotations: null
        from:
          kind: DockerImage
          name: 'docker-registry.default.svc:5000/dqszvc-tools/python-36-rhel7:1-36'
        importPolicy: {}
        referencePolicy:
          type: Local
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: '${NAME}'
    creationTimestamp: null
    annotations:
      description: Python Runtime Image
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: false
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: '${NAME}${SUFFIX}'
    creationTimestamp: null
    labels: {}
    annotations: {}
  spec:
    completionDeadlineSeconds: 12000
    triggers:
      - type: ConfigChange
      - type: ImageChange
    runPolicy: SerialLatestOnly
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: document-manager-base.dockerfile
        env: []
    output:
      to:
        kind: ImageStreamTag
        name: '${NAME}${SUFFIX}:latest'
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
        memory: 1Gi
    postCommit: {}
    nodeSelector: null
