kind: Template
apiVersion: v1
metadata:
  name: document-manager-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: false
    value: latest
  - name: SOURCE_CONTEXT_DIR
    value: prime-database-backup
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/moh-prime
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
    value: dqszvc
  - name: OC_APP
    required: true
    value: dev
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: document-manager-backend
    name: document-manager-backend
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: document-manager-backend
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/bcgov/moh-prime.git
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: document-manager-backend
    name: document-manager-backend
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: document-manager-backend:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: document-manager/backend/
      git:
        ref: feature/PRIME-805-document-manager-template
        uri: https://github.com/bcgov/moh-prime.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
