kind: Template
apiVersion: v1
metadata:
  name: document-manager-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A suffix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: false
    value: latest
  - name: SOURCE_CONTEXT_DIR
    value: document-manager/backend
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/moh-prime
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
    value: dqszvc
  - name: OC_APP
    required: true
    value: dev
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      creationTimestamp: null
      labels:
        shared: 'true'
      annotations:
        description: Keeps track of changes in the application image
    spec:
      lookupPolicy:
        local: false
      tags: []
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      creationTimestamp: null
      annotations:
        description: Defines how to build the application
    spec:
      completionDeadlineSeconds: 600
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: SerialLatestOnly
      source:
        type: Git
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        contextDir: '${SOURCE_CONTEXT_DIR}'
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: '${NAME}-base${SUFFIX}:latest'
          env:
            - name: SUFFIX
              value: ${SUFFIX}
            - name: BUILD_LOGLEVEL
              value: '2'
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}${SUFFIX}:latest'
      resources:
        limits:
          cpu: 200m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      nodeSelector: null
