kind: Template
apiVersion: v1
metadata:
  name: github-runner-dc
  annotations:
    openshift.io/display-name: gitlab-runner
parameters:
  - name: NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
    value: gitlab-runner
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: 'dqszvc'
  - name: OC_APP
    required: true
    value: 'tools'
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: '${NAME}'
    spec:
      selector:
        name: '${NAME}'
      type: ClusterIP
      sessionAffinity: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: '${NAME}'
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
    spec:
      strategy:
        type: Recreate
        maxSurge: 50%
        maxUnavailable: 0
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - gitlab-runner
            from:
              kind: ImageStreamTag
              name: 'gitlab-runner-openshift:latest'
              namespace: dqszvc-tools
            lastTriggeredImage: ''
        - type: ConfigChange
      replicas: 1
      selector:
        name: '${NAME}'
      template:
        metadata:
          labels:
            name: '${NAME}'
        spec:
          containers:
            - name: gitlab-runner
              image: ' '
              env:
                - name: RUNNER_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: RUNNER_USER
                  value: gitlab-runner
                - name: RUNNER_WORKING_DIR
                  value: /home/gitlab-runner
                - name: RUNNER_SCRIPTS_DIR
                  value: /scripts
                - name: RUNNER_SCRIPTS_BACKUP_DIR
                  value: /home/gitlab-runner/scripts.bak
              resources: {}
              imagePullPolicy: IfNotPresent
              capabilities: {}
          restartPolicy: Always
          dnsPolicy: ClusterFirst

