kind: Template
apiVersion: v1
metadata:
  name: mailhog-server-bc
  creationTimestamp: null
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: 'dqszvc'
  - name: OC_APP
    required: true
    value: 'tools'
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: 'mailhog-server'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: 'mailhog-server'
          annotations: null
          from:
            kind: ImageStreamTag
            name: 'mailhog:latest'
            namespace: ${OC_NAMESPACE}-${OC_APP}
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
