apiVersion: v1
kind: Template
labels:
  template: mailhog-server
metadata:
  creationTimestamp: null
  name: -mailhog-server-dc
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: 'dqszvc'
  - name: OC_APP
    required: true
    value: 'tools'
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      ports:
      - name: "1025"
        port: 1025
        targetPort: 1025
      - name: "25"
        port: 25
        targetPort: 1025
      - name: "80"
        port: 80
        targetPort: 8025
      selector:
        io.kompose.service: mailhog-server
    status:
      loadBalancer: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      tags:
      - annotations: null
        from:
          kind: ImageStreamTag
          name: mailhog:latest
        generation: null
        importPolicy: {}
        name: latest
    status:
      dockerImageRepository: ""
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      creationTimestamp: '2019-11-18T20:39:48Z'
      labels:
        io.kompose.service: mailhog-server
        template: mailhog-server
      name: mailhog-25
      namespace: dqszvc-tools
      resourceVersion: '1143485879'
      selfLink: /apis/route.openshift.io/v1/namespaces/dqszvc-tools/routes/mailhog-25
      uid: 90403e3d-0a43-11ea-a81b-0050568379a2
    spec:
      host: mailhog-25-dqszvc-tools.pathfinder.gov.bc.ca
      port:
        targetPort: '25'
      to:
        kind: Service
        name: mailhog-server
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - lastTransitionTime: '2019-11-18T20:39:48Z'
              status: 'True'
              type: Admitted
          host: mailhog-25-dqszvc-tools.pathfinder.gov.bc.ca
          routerName: router
          wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      creationTimestamp: '2019-11-18T20:40:16Z'
      labels:
        io.kompose.service: mailhog-server
        template: mailhog-server
      name: mailhog
      namespace: dqszvc-tools
      resourceVersion: '1143487353'
      selfLink: /apis/route.openshift.io/v1/namespaces/dqszvc-tools/routes/mailhog
      uid: a09c3218-0a43-11ea-a81b-0050568379a2
    spec:
      host: mailhog-dqszvc-tools.pathfinder.gov.bc.ca
      port:
        targetPort: '1025'
      to:
        kind: Service
        name: mailhog-server
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - lastTransitionTime: '2019-11-18T20:40:16Z'
              status: 'True'
              type: Admitted
          host: mailhog-dqszvc-tools.pathfinder.gov.bc.ca
          routerName: router
          wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      creationTimestamp: '2019-11-18T20:38:43Z'
      labels:
        io.kompose.service: mailhog-server
        template: mailhog-server
      name: mailhog-web
      namespace: dqszvc-tools
      resourceVersion: '1143482813'
      selfLink: /apis/route.openshift.io/v1/namespaces/dqszvc-tools/routes/mailhog-web
      uid: 6947e9a5-0a43-11ea-a81b-0050568379a2
    spec:
      host: mailhog-web-dqszvc-tools.pathfinder.gov.bc.ca
      port:
        targetPort: '80'
      to:
        kind: Service
        name: mailhog-server
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - lastTransitionTime: '2019-11-18T20:38:43Z'
              status: 'True'
              type: Admitted
          host: mailhog-web-dqszvc-tools.pathfinder.gov.bc.ca
          routerName: router
          wildcardPolicy: None
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: mailhog-server
      name: mailhog-server
    spec:
      replicas: 1
      selector:
        io.kompose.service: mailhog-server
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: mailhog-server
        spec:
          containers:
          - image: ' '
            name: mailhog-server
            ports:
            - containerPort: 1025
            - containerPort: 1025
            - containerPort: 8025
            resources: {}
          restartPolicy: Always
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - mailhog-server
          from:
            kind: ImageStreamTag
            name: mailhog:latest
        type: ImageChange
    status: {}

