apiVersion: v1
kind: Template
labels:
  template: metabase-postgresql-template
message: |-
  The following service(s) have been created in your project:
    1. ${METABASE_SERVICE_NAME}
    2. ${METABASE_SERVICE_NAME}-postgresql
metadata:
  name: metabase
  annotations:
    openshift.io/display-name: "Metabase backed by PostgreSQL"
    openshift.io/long-description: >
      This template provides a Metabase instance backed by a standalone PostgreSQL
      server. The database is stored on persistent storage.
    description: >
      This is a PostgreSQL backed Metabase (http://www.metabase.com/) deployment. Metabase is the
      easy, open source way for everyone in your company to ask questions and learn from data.
    iconClass: "pficon-trend-up"
    tags: analytics,database,metabase
parameters:
- name: METABASE_SERVICE_NAME
  displayName: Metabase Service Name
  value: metabase
  required: true
- name: METABASE_ROUTE_HOST
  displayName: Metabase Route Host (FQDN)
  description: The hostname to use when creating an OpenShift Route (Leave blank to use defaults.)
  value: ""
  required: false
- name: METABASE_IMAGE
  displayName: Metabase Docker Image
  value: registry.hub.docker.com/metabase/metabase:latest
  description: The metabase docker image to use
  required: true
- description: Version of PostgreSQL image to be used (9.4, 9.5, 9.6 or latest).
  displayName: Version of PostgreSQL Image
  name: POSTGRESQL_VERSION
  required: true
  value: "9.6"
- name: POSTGRESQL_IMAGE_NAMESPACE
  displayName: PostgreSQL Image Namespace
  value: openshift
  description: The OpenShift namespace for the postgresql image to use
  required: true
- name: POSTGRESQL_DATABASE
  displayName: PostgreSQL Database
  description: Database name to use
  value: metabase
  required: true
- name: POSTGRESQL_USER
  displayName: PostgreSQL Username
  description: Username for metabase database user
  value: metabase
  required: true
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQL Password
  description: Password for metabase database user
  generate: expression
  from: "[a-zA-Z0-9]{32}"
  required: true
- name: POSTGRESQL_VOLUME_CAPACITY
  displayName: Database Data Volume Capacity
  description: Capacity required for the PostgreSQL database data volume
  value: 1Gi
  required: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: metabase
    name: ${METABASE_SERVICE_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${METABASE_IMAGE}
      generation: 2
      name: latest
      referencePolicy:
        type: Source
