kind: Template
apiVersion: v1
metadata:
  name: postgresql-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
  - name: OC_APP
    required: true
objects:
  - apiVersion: v1
    data:
      database-admin-password: cG9zdGdyZXM=
      database-name: cG9zdGdyZXM=
      database-password: cG9zdGdyZXM=
      database-user: cG9zdGdyZXM=
    kind: Secret
    metadata:
      creationTimestamp: null
      name: '${NAME}${SUFFIX}-secret'
      namespace: '${OC_NAMESPACE}-${OC_APP}'
      resourceVersion: null
      selfLink: >-
        /api/v1/namespaces/${OC_NAMESPACE}-${OC_APP}/secrets/${NAME}${SUFFIX}-secret
      uid: null
    type: Opaque
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${NAME}'
          annotations: null
          from:
            kind: ImageStreamTag
            name: 'postgresql:latest'
            namespace: 'openshift'
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
