apiVersion: v1
kind: Template
labels:
  template: postgresql-persistent-template
metadata:
  creationTimestamp: null
  name: postgresql-dc
parameters:
  - description: The name of the OpenShift Service exposed for the database.
    displayName: Database Service Name
    name: NAME
    required: true
  - name: VERSION
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: SUFFIX
    required: false
  - name: OC_NAMESPACE
    required: true
  - name: OC_APP
    required: true
  - description: The name of the OpenShift Service exposed for the database.
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: postgresql
  - description: The OpenShift ImageStream name.
    displayName: IMAGE_STREAM_NAME
    name: IMAGE_STREAM_NAME
    value: postgresql
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: IMAGE_STREAM_NAMESPACE
    value: ''
  - description: 'Version of PostgreSQL image to be used (9.2, 9.4, 9.5 or latest).'
    displayName: Version of PostgreSQL Image
    name: IMAGE_STREAM_VERSION
    required: true
    value: '9.6'
  - description: Name of the PostgreSQL database accessed.
    displayName: PostgreSQL Database Name
    name: POSTGRESQL_DATABASE
    required: true
    value: postgresQL
  - description: 'Volume space available for data, e.g. 512Mi, 2Gi.'
    displayName: Volume Capacity
    name: VOLUME_CAPACITY
    required: true
    value: 1Gi
  - name: CPU_LIMIT
    value: 500m
  - name: MEMORY_LIMIT
    value: 2Gi
  - name: CPU_REQUEST
    value: 200m
  - name: MEMORY_REQUEST
    value: 1.5Gi
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: >-
          postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
      name: '${NAME}${SUFFIX}'
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: '${NAME}${SUFFIX}'
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: '${NAME}${SUFFIX}'
      annotations:
        volume.beta.kubernetes.io/storage-class: gluster-file-db
        volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: '${VOLUME_CAPACITY}'
  - apiVersion: v1
    data:
      database-admin-password: cG9zdGdyZXM=
      database-name: cG9zdGdyZXM=
      database-password: cG9zdGdyZXM=
      database-user: cG9zdGdyZXM=
    kind: Secret
    metadata:
      creationTimestamp: null
      name: '${NAME}${SUFFIX}-secret'
      namespace: '${OC_NAMESPACE}-${OC_APP}'
      resourceVersion: null
      selfLink: >-
        /api/v1/namespaces/${OC_NAMESPACE}-${OC_APP}/secrets/${NAME}${SUFFIX}-secret
      uid: null
    type: Opaque
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      creationTimestamp: null
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: '${NAME}${SUFFIX}'
    spec:
      replicas: 1
      selector:
        name: '${NAME}${SUFFIX}'
      strategy:
        type: Recreate
        maxSurge: 50%
        maxUnavailable: 0
      template:
        metadata:
          labels:
            name: '${NAME}${SUFFIX}'
        spec:
          containers:
            - capabilities: {}
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: '${NAME}${SUFFIX}-secret'
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: '${NAME}${SUFFIX}-secret'
                - name: POSTGRESQL_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: '${NAME}${SUFFIX}-secret'
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: '${NAME}${SUFFIX}-secret'
              image: ' '
              imagePullPolicy: IfNotPresent
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - '-i'
                    - '-c'
                    - >-
                      psql -h 127.0.0.1 -d $POSTGRESQL_DATABASE -U
                      $POSTGRESQL_USER -c 'SELECT 1'
                initialDelaySeconds: 5
                timeoutSeconds: 1
              resources:
                requests:
                  cpu: '${CPU_REQUEST}'
                  memory: '${MEMORY_REQUEST}'
                limits:
                  cpu: '${CPU_LIMIT}'
                  memory: '${MEMORY_LIMIT}'
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: '${NAME}${SUFFIX}-data'
                - mountPath: /var/run/postgresql
                  name: '${NAME}${SUFFIX}-run'
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: '${NAME}${SUFFIX}-data'
              persistentVolumeClaim:
                claimName: '${NAME}${SUFFIX}'
            - name: '${NAME}${SUFFIX}-run'
              emptyDir: {}
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: 'postgresql:9.6'
              namespace: openshift
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange
    status: {}
