kind: Template
apiVersion: v1
metadata:
  annotations:
    description: SchemaSpy build template.
    tags: schema-spy
  name: "${APP_NAME}-bc"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APP_NAME}"
      labels:
        app: "${APP_NAME}"
        buildconfig: "${APP_NAME}"
    spec:
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
      triggers:
      - type: ConfigChange
      - type: ImageChange
parameters:
  - name: APP_NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: schema-spy
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to the Git repository.
    required: true
    value: https://github.com/bcgov/moh-prime.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: develop
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: ''
