kind: Template
apiVersion: v1
metadata:
  name: schemaspy-bc
  annotations:
    description: SchemaSpy build template.
    tags: schema-spy
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: "schemaspy"
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to the Git repository.
    required: true
    value: https://github.com/bcgov/moh-prime.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: develop
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: ''
  - name: OC_NAMESPACE
    required: true
  - name: OC_APP
    required: true
  - name: "SOURCE_REPOSITORY_REF"
    required: false
  - name: "SOURCE_REPOSITORY_URL"
    required: false
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
      labels:
        app: "${NAME}${SUFFIX}"
        buildconfig: "${NAME}${SUFFIX}"
    spec:
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}${SUFFIX}:latest"
      triggers:
      - type: ConfigChange
      - type: ImageChange
