kind: Template
apiVersion: v1
metadata:
  name: schemaspy-bc
  annotations:
    description: SchemaSpy build template.
    tags: schema-spy
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: true
    value: 'develop'
  - name: OC_NAMESPACE
    required: true
    value: 'dqszvc'
  - name: OC_APP
    required: true
    value: 'tools'
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}${SUFFIX}"
      labels:
        app: "${NAME}${SUFFIX}"
        buildconfig: "${NAME}${SUFFIX}"
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}${SUFFIX}:latest"
      triggers:
      - type: ConfigChange
      - type: ImageChange
