kind: Template
apiVersion: v1
metadata:
  name: sonar-scanner-bc
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SUFFIX
    displayName: Name Suffix
    description: A suffix appended to all objects
    required: false
  - name: VERSION
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
    value: ""
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_NAMESPACE
    required: true
  - name: OC_APP
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec: {}
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        kompose.cmd: >-
          kompose convert --provider=openshift --build=build-config
          --build-repo=https://github.com/bcgov/moh-prime.git
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: '${NAME}${SUFFIX}'
      name: '${NAME}${SUFFIX}'
    spec:
      completionDeadlineSeconds: 6000
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}${SUFFIX}:latest'
      postCommit: {}
      resources:
        requests:
          cpu: '2'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 8Gi
      runPolicy: Serial
      source:
        contextDir: '${SOURCE_CONTEXT_DIR}'
        git:
          ref: '${SOURCE_REPOSITORY_REF}'
          uri: '${SOURCE_REPOSITORY_URL}'
        type: Git
      strategy:
        dockerStrategy: 
          dockerfilePath: openshift.dockerfile
        type: Docker
      triggers:
        - type: ConfigChange
        - type: ImageChange
    status:
      lastVersion: 0

