kind: Template
apiVersion: v1
metadata:
  name: sonar-scanner-bc
  creationTimestamp: null
parameters:
  - name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/bcgov/moh-prime'
  - name: SOURCE_REPOSITORY_REF
    required: false
    value: 'develop'
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec: {}
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: sonar-runner:latest
      postCommit: {}
      resources: 
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: '1'
          memory: 1024Mi
      runPolicy: Serial
      source:
        contextDir: sonar-scanner/
        git:
          ref: '${SOURCE_REPOSITORY_REF}'
          uri: '${SOURCE_REPOSITORY_URL}'
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: openshift.dockerfile
        type: Docker
      triggers:
      - type: ConfigChange
      - type: ImageChange
    status:
      lastVersion: 0
