kind: Template
apiVersion: v1
metadata:
  name: sonar-scanner-bc
  creationTimestamp: null
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec: {}
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: sonar-runner:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: sonar-scanner/
        git:
          ref: feature/sonar-scanner-phase-3
          uri: https://github.com/bcgov/moh-prime.git
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: openshift.dockerfile
        type: Docker
      triggers:
      - type: ConfigChange
      - type: ImageChange
    status:
      lastVersion: 0
