kind: Template
apiVersion: v1
metadata:
  name: sonar-scanner-dc
  creationTimestamp: null
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec:
      replicas: 1
      selector:
        io.kompose.service: sonar-runner
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: sonar-runner
        spec:
          containers:
            - env:
                - name: JAVA_HOME
                  value: '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/bin'
                - name: PATH
                  value: '$PATH:$JAVA_HOME:/var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQubeScanner/bin:/home/default/.dotnet/tools'
          - image: ' '
            name: sonar-scanner
            resources: {}
          restartPolicy: Always
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - sonar-scanner
          from:
            kind: ImageStreamTag
            name: sonar-runner:latest
        type: ImageChange
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-runner
      name: sonar-runner
    spec:
      clusterIP: None
      ports:
      - name: headless
        port: 55555
        targetPort: 0
      selector:
        io.kompose.service: sonar-runner
    status:
      loadBalancer: {}
