apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: backup
  name: backup
spec:
  ports:
  - name: "6432"
    port: 6432
    targetPort: 5432
  selector:
    io.kompose.service: backup
status:
  loadBalancer: {}
