apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backup
  name: backup
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: backup
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
