apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: backup
  name: backup
spec:
  replicas: 1
  selector:
    io.kompose.service: backup
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/primenet: "true"
        io.kompose.service: backup
    spec:
      containers:
      - image: ' '
        name: backup
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /opt/backup
          name: backup-postgres-data
        - mountPath: /var/lib/postgresql/data
          name: local-postgres-data
      restartPolicy: Always
      volumes:
      - name: backup-postgres-data
        persistentVolumeClaim:
          claimName: backup-postgres-data
      - name: local-postgres-data
        persistentVolumeClaim:
          claimName: local-postgres-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - backup
      from:
        kind: ImageStreamTag
        name: backup:latest
    type: ImageChange
status: {}
