apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: backup
  name: backup
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backup:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: prime-database-backup/
    git:
      ref: feature/database-backup
      uri: https://github.com/bcgov/moh-prime.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
