apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: document-manager-backend
  name: document-manager-backend
spec:
  replicas: 1
  selector:
    io.kompose.service: document-manager-backend
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/primenet: "true"
        io.kompose.service: document-manager-backend
    spec:
      containers:
      - env:
        - name: CACHE_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: CACHE_REDIS_HOST
              name: document-manager-backend--env-prime
        - name: CACHE_REDIS_PASS
          valueFrom:
            configMapKeyRef:
              key: CACHE_REDIS_PASS
              name: document-manager-backend--env-prime
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: document-manager-backend--env-prime
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: document-manager-backend--env-prime
        - name: DB_NAME_TEST
          valueFrom:
            configMapKeyRef:
              key: DB_NAME_TEST
              name: document-manager-backend--env-prime
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              key: DB_PASS
              name: document-manager-backend--env-prime
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: document-manager-backend--env-prime
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: document-manager-backend--env-prime
        - name: DOCUMENT_MANAGER_URL
          valueFrom:
            configMapKeyRef:
              key: DOCUMENT_MANAGER_URL
              name: document-manager-backend--env-prime
        - name: ELASTIC_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ELASTIC_ENABLED
              name: document-manager-backend--env-prime
        - name: ELASTIC_SECRET_TOKEN
          valueFrom:
            configMapKeyRef:
              key: ELASTIC_SECRET_TOKEN
              name: document-manager-backend--env-prime
        - name: ELASTIC_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: ELASTIC_SERVER_URL
              name: document-manager-backend--env-prime
        - name: ELASTIC_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              key: ELASTIC_SERVICE_NAME
              name: document-manager-backend--env-prime
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: document-manager-backend--env-prime
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              key: FLASK_DEBUG
              name: document-manager-backend--env-prime
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              key: FLASK_ENV
              name: document-manager-backend--env-prime
        - name: FLASK_RUN_HOST
          valueFrom:
            configMapKeyRef:
              key: FLASK_RUN_HOST
              name: document-manager-backend--env-prime
        - name: FLASK_RUN_PORT
          valueFrom:
            configMapKeyRef:
              key: FLASK_RUN_PORT
              name: document-manager-backend--env-prime
        - name: JWT_OIDC_ALGORITHMS
          valueFrom:
            configMapKeyRef:
              key: JWT_OIDC_ALGORITHMS
              name: document-manager-backend--env-prime
        - name: JWT_OIDC_AUDIENCE
          valueFrom:
            configMapKeyRef:
              key: JWT_OIDC_AUDIENCE
              name: document-manager-backend--env-prime
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: JWT_OIDC_WELL_KNOWN_CONFIG
              name: document-manager-backend--env-prime
        image: ' '
        name: document-manager-backend
        ports:
        - containerPort: 6001
        resources: {}
        volumeMounts:
        - mountPath: /app/
          name: document-manager-backend-claim0
      restartPolicy: Always
      volumes:
      - name: document-manager-backend-claim0
        persistentVolumeClaim:
          claimName: document-manager-backend-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - document_manager_backend
      from:
        kind: ImageStreamTag
        name: document-manager-backend:latest
    type: ImageChange
status: {}
