apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/bcgov/moh-prime.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: document-manager-backend
  name: document-manager-backend
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: document-manager-backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: document-manager/backend/
    git:
      ref: feature/PRIME-676-business-licence-upload
      uri: https://github.com/bcgov/moh-prime.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
