apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: document-manager-backend
  name: document-manager-backend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: document-manager-backend
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
