apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dotnet-webapi
  name: dotnet-webapi
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: dotnet-webapi
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
