apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  creationTimestamp: '2019-10-05T15:16:54Z'
  generation: 6
  labels:
    template: jenkins-persistent-template
    template.openshift.io/template-instance-owner: 29e3deea-e783-11e9-8615-0050568348cc
  name: jenkins-prod
  namespace: 9c33a9-tools
  resourceVersion: '1074231876'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/9c33a9-tools/deploymentconfigs/jenkins-prod
  uid: 29f6e4b1-e783-11e9-8615-0050568348cc
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    name: jenkins-prod
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jenkins-prod
    spec:
      containers:
        - env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: 'true'
            - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
              value: 'true'
            - name: OPENSHIFT_JENKINS_JVM_ARCH
              value: x86_64
            - name: KUBERNETES_MASTER
              value: 'https://kubernetes.default:443'
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: 'true'
            - name: JNLP_SERVICE_NAME
              value: jenkins-jnlp
            - name: JAVA_OPTS
              value: >-
                -XX:MaxMetaspaceSize=512m -Duser.timezone=America/Vancouver
                -Dhudson.model.DirectoryBrowserSupport.CSP=
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/jenkins@sha256:36f8501570cd2846cc93f34a53010f3971803876bf11362399267fcd0368feb2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: jenkins-prod-data
            - mountPath: /backup
              name: volume-8gxdz
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins-prod
      serviceAccountName: jenkins-prod
      terminationGracePeriodSeconds: 30
      volumes:
        - name: jenkins-prod-data
          persistentVolumeClaim:
            claimName: jenkins-prod
        - name: volume-8gxdz
          persistentVolumeClaim:
            claimName: jenkins-prod-home
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
        from:
          kind: ImageStreamTag
          name: 'jenkins:2'
          namespace: openshift
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/openshift/jenkins@sha256:36f8501570cd2846cc93f34a53010f3971803876bf11362399267fcd0368feb2
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 0
  conditions:
    - lastTransitionTime: '2019-10-31T02:19:38Z'
      lastUpdateTime: '2019-10-31T02:20:23Z'
      message: replication controller "jenkins-prod-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2019-10-31T02:32:38Z'
      lastUpdateTime: '2019-10-31T02:32:38Z'
      message: Deployment config does not have minimum availability.
      status: 'False'
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 6
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
