apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-angular
  name: nginx-angular
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nginx-angular
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
