# Default values for prime-webapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  vanityURL: "pharmanetenrolment.gov.bc.ca"
  image:
    registry: image-registry.openshift-image-registry.svc:5000/9c33a9-tools
    tag: latest

replicaCount: 1

image:
  repository: prime-webapi-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: "webapi"
fullnameOverride: ""

cache:
  redisUrl: 'redis://localhost:6379'
  # If secret exists, it should contain key "redis_url". specify the name of the secret below.
  # existingSecret: ''

database:
  autoCreate: true
  autoCreatePip: true
  # .NET Core database connection string
  dbConnectionString: 'host=postgres;port=5432;database=postgres;username=postgres;password=postgres'
  # If secret exists, it should contain key "database_url". specify the name of the secret below.
  # existingSecret:

# Run migrations pre-install and pre-upgrade
migrations:
  enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
