# This workflow will build all of the necessary components for the PRIME 
# application, with the respective images pushed and stored in the project's
# tools namespace.
#
# Images are then deployed to the respective OpenShift namespace via the
# prime-app-template.yml in the infrastructure folder.

name: Build Demo

on:
  push:
    branches:
      - master

  workflow_dispatch:
    branches:
      - master

jobs:
  build-document-manager-backend:
    runs-on: ubuntu-20.04
    environment: Test
    env:
      BUILD_LOGLEVEL: "2"
      SERVICE_NAME: document-manager
      CONTAINER_NAME: prime-document-manager
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: "Login to OpenShift repository"
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_USERNAME}}
          password: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_PASSWORD}}

      - name: "Login to RedHat container repository"
        uses: docker/login-action@v1
        with: 
          registry: ${{secrets.REDHAT_REGISTRY_URL}}
          username: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USER}}
          password: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_AUTH_TOKEN}}

      - name: "Build and Push: Document Manager"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: document-manager/backend
          file: document-manager/backend/openshift.dockerfile
          build-args: |
            BUILD_LOGLEVEL=$BUILD_LOGLEVEL
            SVC_NAME="demo"
          tags: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-document-manager:demo
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

      # - name: "Build, tag and push Document Manager image"
      #   id: build-image
      #   env:
      #     COMPOSE_DOCKER_CLI_BUILD: 1
      #     DOCKER_BUILDKIT: 1
      #     BUILD_LOGLEVEL: 2
      #   run: |
      #     docker-compose -f oc4-compose.yml build --force-rm --no-cache \
      #       --build-arg BUILD_LOGLEVEL=$BUILD_LOGLEVEL \
      #       --build-arg SVC_NAME="demo" \
      #       $SERVICE_NAME
      #     docker tag moh-prime_$SERVICE_NAME ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo
      #     docker image push ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo

  build-weapi:
    runs-on: ubuntu-20.04
    environment: Test
    env:
      SERVICE_NAME: dotnet-webapi
      CONTAINER_NAME: prime-webapi-backend
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: "Login to OpenShift repository"
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_USERNAME}}
          password: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_PASSWORD}}

      - name: "Login to RedHat container repository"
        uses: docker/login-action@v1
        with: 
          registry: ${{secrets.REDHAT_REGISTRY_URL}}
          username: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USER}}
          password: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_AUTH_TOKEN}}

      - name: "Build and Push: Webapi"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: prime-dotnet-webapi/
          file: prime-dotnet-webapi/openshift.dockerfile
          build-args: |
            ASPNETCORE_HTTPS_PORT=5001
            ASPNETCORE_ENVIRONMENT="Development"
            ASPNETCORE_URLS="http://+:8080"
            DB_CONNECTION_STRING="host=dev-postgres;port=5432;database=prime-dev;username=${{secrets.PRIME_DB_USER}};password=${{secrets.PRIME_DB_PASSWORD}}"
            DB_HOST=dev-postgres
            DOTNET_CLI_HOME="/tmp/DOTNET_CLI_HOME"
            PGPASSWORD=${{secrets.PRIME_DB_PASSWORD}}
            POSTGRESQL_ADMIN_PASSWORD=${{secrets.PRIME_DB_PASSWORD}}
            POSTGRESQL_USERNAME=${{secrets.PRIME_DB_USER}}
            POSTGRESQL_DATABASE=prime-dev
            SVC_NAME="demo"
          tags: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/prime-webapi-backend:demo
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

      # - name: "Build, tag and push .NET web API image"
      #   id: build-image
      #   env:
      #     PRIME_DB_PASSWORD: ${{secrets.PRIME_DB_PASSWORD}}
      #     PRIME_DB_USER: ${{secrets.PRIME_DB_USER}}
      #     COMPOSE_DOCKER_CLI_BUILD: 1
      #     DOCKER_BUILDKIT: 1

      #   run: |
      #     docker-compose -f oc4-compose.yml build --force-rm --no-cache \
      #       --build-arg ASPNETCORE_HTTPS_PORT=5001 \
      #       --build-arg ASPNETCORE_ENVIRONMENT="Development" \
      #       --build-arg ASPNETCORE_URLS="http://+:8080" \
      #       --build-arg DB_CONNECTION_STRING="host=demo-postgres-db;port=5432;database=prime-demo;username=$PRIME_DB_USER;password=$PRIME_DB_PASSWORD" \
      #       --build-arg DB_HOST=demo-postgres-db \
      #       --build-arg DOTNET_CLI_HOME="/tmp/DOTNET_CLI_HOME" \
      #       --build-arg PGPASSWORD=$PRIME_DB_PASSWORD \
      #       --build-arg POSTGRESQL_ADMIN_PASSWORD=$PRIME_DB_PASSWORD \
      #       --build-arg POSTGRESQL_USERNAME=$PRIME_DB_USER \
      #       --build-arg POSTGRESQL_DATABASE=prime-demo \
      #       --build-arg SVC_NAME="demo" \
      #       $SERVICE_NAME
      #     docker tag moh-prime_$SERVICE_NAME ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo
      #     docker image push ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo

  build-frontend:
    runs-on: ubuntu-20.04
    environment: Test
    env:
      SERVICE_NAME: nginx-angular
      CONTAINER_NAME: prime-frontend
      JWT_WELL_KNOWN_CONFIG: "https://test.oidc.gov.bc.ca/auth/realms/v4mbqqas/.well-known/openid-configuration"
      KEYCLOAK_CLIENT_ID: "prime-application-test"
      KEYCLOAK_URL: "https://test.oidc.gov.bc.ca/auth"
      KEYCLOAK_REALM: "v4mbqqas"
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: "Login to OpenShift repository"
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_USERNAME}}
          password: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_PASSWORD}}

      - name: "Login to RedHat container repository"
        uses: docker/login-action@v1
        with: 
          registry: ${{secrets.REDHAT_REGISTRY_URL}}
          username: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USER}}
          password: ${{secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_AUTH_TOKEN}}

      - name: "Build, tag & push Angular frontend image"
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          REDIRECT_URL: "https://demo.pharmanetenrolment.gov.bc.ca"       
        run: |
          docker-compose -f oc4-compose.yml build --force-rm --no-cache \
            --build-arg JWT_WELL_KNOWN_CONFIG=${{env.$JWT_WELL_KNOWN_CONFIG}} \
            --build-arg KEYCLOAK_URL=${{env.$KEYCLOAK_URL}} \
            --build-arg KEYCLOAK_REALM=${{env.$KEYCLOAK_REALM}} \
            --build-arg KEYCLOAK_CLIENT_ID=${{env.$KEYCLOAK_CLIENT_ID}} \
            --build-arg OC_APP=${{secrets.OC_APP}} \
            --build-arg SVC_NAME="demo" \
            --build-arg REDIRECT_URL=${{env.$REDIRECT_URL}} \
            $SERVICE_NAME
          docker tag moh-prime_$SERVICE_NAME ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo
          docker image push ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/$CONTAINER_NAME:demo

  apply-oc-template:
    runs-on: ubuntu-20.04
    needs: [build-document-manager,build-frontend,build-webapi]
    environment: Test
    steps:
      - name: "Use the OpenShift template"
        uses: actions/checkout@v2

      - name: Install OC
        uses: redhat-actions/oc-installer@v1

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_SERVICE_TOKEN}}
          namespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{secrets.OC_APP}}

      - name: "Process template"
        id: oc
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1

        run: |
          oc process -f infrastructure/prime-app-template.yml \
            -p ASP_ENV=Development \
            -p VANITY_URL=demo.pharmanetenrolment.gov.bc.ca \
            -p IMAGE_TAG=demo \
            -p SVC_NAME=demo \
            -p OC_NAMESPACE=${{secrets.OPENSHIFT_LICENSE_PLATE}} \
            -p OC_APP=${{secrets.OC_APP}} \
            -p URL_STUB=-${{secrets.OPENSHIFT_LICENSE_PLATE}}-demo.apps.silver.devops.gov.bc.ca \
            -p WEB_PORT=8080 \
            -p HPR_URL=demo-hpr-${{secrets.OPENSHIFT_LICENSE_PLATE}}-demo.apps.silver.devops.gov.bc.ca \
            -p MAUTH_URL=demo-mauth-${{secrets.OPENSHIFT_LICENSE_PLATE}}-demo.apps.silver.devops.gov.bc.ca \
            -n ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{secrets.OC_APP}} | oc apply -n ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{secrets.OC_APP}} -f -